/* JK Works Dordrecht - persoonlijke PWA v7 */
const App = (() => {
  const state = {route:'dashboard',gearTab:'mboxes',docFolder:'all',importFolderTarget:'diversen',pdfLibPromise:null};
  const PDFLIB_URL='https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/dist/pdf-lib.min.js';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=(v='')=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const money=v=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(Number(v||0));
  const num=v=>{const n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)?n:0};
  const pad=n=>String(n).padStart(2,'0');
  const today=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
  const addDays=(iso,days)=>{const d=new Date(`${iso}T12:00:00`);d.setDate(d.getDate()+days);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
  const nlDate=iso=>{if(!iso)return '';const m=String(iso).match(/^(\d{4})-(\d{2})-(\d{2})$/);if(m)return `${m[3]}-${m[2]}-${m[1]}`;const d=new Date(iso);return Number.isNaN(+d)?String(iso):new Intl.DateTimeFormat('nl-NL').format(d)};
  const fmtDateTime=v=>v?new Intl.DateTimeFormat('nl-NL',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'-';
  const durationHM=min=>`${Math.floor(min/60)}:${pad(Math.round(min%60))}`;

  async function init(){
    await JKDB.open(); window.__JK_SEEDING=true; try{await JKDB.seed();}finally{window.__JK_SEEDING=false;} await JKCloud.init(); bindNav(); bindInputs(); bindCloudEvents(); registerSW(); await render();
    if(navigator.onLine) setTimeout(()=>ensurePdfLib().catch(()=>{}),1000);
  }
  function bindCloudEvents(){document.addEventListener('jkcloud-auth',()=>render());document.addEventListener('jkcloud-sync',e=>{if(e.detail?.state==='done'&&e.detail?.changed&&!$('#modalRoot').children.length)render();});}
  function registerSW(){if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./service-worker.js').catch(()=>{});}
  function ensurePdfLib(){
    if(window.PDFLib)return Promise.resolve(window.PDFLib);
    if(state.pdfLibPromise)return state.pdfLibPromise;
    state.pdfLibPromise=new Promise((resolve,reject)=>{
      const s=document.createElement('script');s.src=PDFLIB_URL;s.async=true;s.crossOrigin='anonymous';
      const t=setTimeout(()=>{state.pdfLibPromise=null;s.remove();reject(new Error('PDF-module kon niet worden geladen. Open de app één keer met internet.'));},18000);
      s.onload=()=>{clearTimeout(t);window.PDFLib?resolve(window.PDFLib):(state.pdfLibPromise=null,reject(new Error('PDF-module niet beschikbaar.')))};
      s.onerror=()=>{clearTimeout(t);state.pdfLibPromise=null;reject(new Error('PDF-module kon niet worden geladen. Controleer je internetverbinding.'));};
      document.head.appendChild(s);
    });
    return state.pdfLibPromise;
  }
  function bindNav(){
    $$('.nav-item').forEach(b=>b.addEventListener('click',()=>go(b.dataset.route)));
    $('#quickAddBtn').addEventListener('click',quickAdd);
  }
  function bindInputs(){
    $('#hiddenExistingPdfInput').addEventListener('change',async e=>{if(e.target.files.length)await importExistingPdfs([...e.target.files],state.importFolderTarget);e.target.value='';});
    $('#hiddenBackupInput').addEventListener('change',async e=>{if(e.target.files[0])await restoreBackup(e.target.files[0]);e.target.value='';});
  }
  async function go(route){state.route=route;$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===route));await render();window.scrollTo({top:0,behavior:'instant'});}
  function title(t){$('#pageTitle').textContent=t}
  function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2200)}
  function modal(html){$('#modalRoot').innerHTML=`<div class="modal-backdrop"><section class="modal">${html}</section></div>`;$('.modal-backdrop').addEventListener('click',e=>{if(e.target.classList.contains('modal-backdrop'))closeModal()});$$('[data-close]').forEach(x=>x.addEventListener('click',closeModal));}
  function closeModal(){$('#modalRoot').innerHTML=''}
  function modalHead(t){return `<div class="modal-head"><h2>${esc(t)}</h2><button class="close-btn" data-close>×</button></div>`}
  async function render(){const v=$('#view');v.innerHTML='<div class="empty">Laden...</div>';try{if(state.route==='dashboard')return renderDashboard();if(state.route==='jobs')return renderJobs();if(state.route==='gear')return renderGear();if(state.route==='documents')return renderDocuments();if(state.route==='more')return renderMore();}catch(e){console.error(e);v.innerHTML=`<div class="card"><h2>Er ging iets mis</h2><p class="muted">${esc(e.message||e)}</p></div>`}}

  function entryMinutes(e){
    if(e.date&&e.from&&e.to){let a=new Date(`${e.date}T${e.from}:00`),b=new Date(`${e.date}T${e.to}:00`);if(b<=a)b.setDate(b.getDate()+1);return Math.max(0,Math.round((b-a)/60000));}
    if(e.start&&e.end)return Math.max(0,Math.round((new Date(e.end)-new Date(e.start))/60000));
    return 0;
  }
  function entryDate(e){return e.date||String(e.start||'').slice(0,10)}
  function entryFrom(e){return e.from||String(e.start||'').slice(11,16)}
  function entryTo(e){return e.to||String(e.end||'').slice(11,16)}

  async function renderDashboard(){
    title('Dashboard');
    const [jobs,docs,entries,backup]=await Promise.all([JKDB.all('jobs'),JKDB.all('documents'),JKDB.all('timeEntries'),JKDB.get('settings','backup')]);
    const month=today().slice(0,7),hours=entries.filter(e=>entryDate(e).startsWith(month)).reduce((s,e)=>s+entryMinutes(e),0)/60;
    const active=jobs.filter(j=>j.status!=='afgerond').length;
    const daysSinceBackup=backup?.lastBackup?Math.floor((Date.now()-new Date(backup.lastBackup))/86400000):999;
    $('#view').innerHTML=`
      ${daysSinceBackup>7?`<div class="warning"><strong>Back-up aanbevolen</strong><br><span class="small">${backup?.lastBackup?'Laatste back-up '+daysSinceBackup+' dagen geleden.':'Nog geen back-up gemaakt.'}</span> <button class="link-btn" id="dashBackup">Nu maken</button></div>`:''}
      <div class="hero brand-hero"><img src="assets/jk-works-logo.jpg" alt="JK Works Dordrecht logo"><div><div class="muted small">Persoonlijke bedrijfsapp</div><h2>JK Works Dordrecht</h2><div class="small">Klussen, inpakchecklists, uren, offertes en facturen.</div></div></div>
      <div class="kpi-row"><div class="kpi"><strong>${active}</strong><span>OPEN KLUSSEN</span></div><div class="kpi"><strong>${docs.length}</strong><span>DOCUMENTEN</span></div><div class="kpi"><strong>${hours.toFixed(1).replace('.',',')}</strong><span>UREN DEZE MAAND</span></div></div>
      <div class="section-title"><h2>Snel openen</h2></div>
      <div class="quick-grid">
        <button class="quick" data-go="gear"><span class="emoji">🧰</span><strong>Inpakchecklists</strong></button>
        <button class="quick" id="newInvoice"><span class="emoji">🧾</span><strong>Nieuwe factuur</strong></button>
        <button class="quick" id="newQuote"><span class="emoji">📄</span><strong>Nieuwe offerte</strong></button>
        <button class="quick" id="addHours"><span class="emoji">🕒</span><strong>Uren invoeren</strong></button>
      </div>`;
    $$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
    $('#newInvoice').addEventListener('click',()=>createBusinessDoc('Factuur'));
    $('#newQuote').addEventListener('click',()=>createBusinessDoc('Offerte'));
    $('#addHours').addEventListener('click',()=>editTimeEntry());
    $('#dashBackup')?.addEventListener('click',exportBackup);
  }

  async function renderJobs(){
    title('Klussen');const jobs=(await JKDB.all('jobs')).sort((a,b)=>(b.date||'').localeCompare(a.date||''));
    $('#view').innerHTML=`<div class="button-row"><button class="primary" id="newJob">+ Nieuwe klus</button></div><div class="section-title"><h2>Klussen</h2></div>${jobs.length?`<div class="list">${jobs.map(j=>`<div class="list-item clickable" data-job="${j.id}"><div class="main"><div class="title">${esc(j.title)}</div><div class="sub">${esc(j.clientName||'Geen klant')} · ${nlDate(j.date)||'geen datum'}</div></div><span class="pill ${j.status==='afgerond'?'success':'warn'}">${esc(j.status||'open')}</span></div>`).join('')}</div>`:'<div class="empty">Nog geen klussen.</div>'}`;
    $('#newJob').addEventListener('click',()=>editJob());$$('[data-job]').forEach(x=>x.addEventListener('click',()=>showJob(x.dataset.job)));
  }
  async function editJob(id){
    const j=id?await JKDB.get('jobs',id):{id:JKDB.id('job'),title:'',clientId:'',clientName:'',date:today(),address:'',status:'open',notes:'',checklistId:'',checklistState:{}};
    const [clients,checks]=await Promise.all([JKDB.all('clients'),JKDB.all('checklists')]);
    modal(`${modalHead(id?'Klus bewerken':'Nieuwe klus')}<form id="jobForm"><div class="field"><label>Omschrijving klus</label><input name="title" required value="${esc(j.title)}"></div><div class="field"><label>Klant</label><select name="clientId"><option value="">Geen / handmatig</option>${clients.map(c=>`<option value="${c.id}" ${j.clientId===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="form-grid"><div class="field"><label>Datum</label><input type="date" name="date" value="${esc(j.date||'')}"></div><div class="field"><label>Status</label><select name="status"><option ${j.status==='open'?'selected':''}>open</option><option ${j.status==='gepland'?'selected':''}>gepland</option><option ${j.status==='afgerond'?'selected':''}>afgerond</option></select></div><div class="field full"><label>Adres</label><input name="address" value="${esc(j.address||'')}"></div><div class="field full"><label>Checklist</label><select name="checklistId"><option value="">Geen</option>${checks.map(c=>`<option value="${c.id}" ${j.checklistId===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="field full"><label>Notities</label><textarea name="notes">${esc(j.notes||'')}</textarea></div></div><div class="button-row"><button class="primary">Opslaan</button>${id?'<button type="button" class="danger-btn" id="delJob">Verwijderen</button>':''}</div></form>`);
    $('#jobForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),client=clients.find(c=>c.id===f.get('clientId'));Object.assign(j,{title:f.get('title'),clientId:f.get('clientId'),clientName:client?.name||'',date:f.get('date'),status:f.get('status'),address:f.get('address'),checklistId:f.get('checklistId'),notes:f.get('notes')});await JKDB.put('jobs',j);closeModal();toast('Klus opgeslagen');render();});
    $('#delJob')?.addEventListener('click',async()=>{if(confirm('Klus verwijderen?')){await JKDB.remove('jobs',j.id);closeModal();render();}});
  }
  async function showJob(id){
    const j=await JKDB.get('jobs',id),entries=(await JKDB.all('timeEntries')).filter(e=>e.jobId===id).sort((a,b)=>entryDate(b).localeCompare(entryDate(a))),check=j.checklistId?await JKDB.get('checklists',j.checklistId):null;
    const checkHtml=check?check.items.map((item,i)=>`<label class="checkline"><input type="checkbox" data-jobcheck="${i}" ${j.checklistState?.[i]?'checked':''}><span>${esc(item)}</span></label>`).join(''):'<span class="muted small">Geen checklist gekoppeld.</span>';
    modal(`${modalHead(j.title)}<div class="button-row"><button class="secondary" id="editThisJob">Bewerken</button><button class="primary" id="hoursThisJob">+ Uren</button></div><div class="card" style="margin-top:10px"><strong>${esc(j.clientName||'Geen klant')}</strong><div class="muted small">${nlDate(j.date)}${j.address?' · '+esc(j.address):''}</div>${j.notes?`<p class="small">${esc(j.notes)}</p>`:''}</div><div class="section-title"><h2>Checklist</h2></div><div class="card">${checkHtml}</div><div class="section-title"><h2>Uren</h2><span class="muted small">${(entries.reduce((s,e)=>s+entryMinutes(e),0)/60).toFixed(2).replace('.',',')} u</span></div>${entries.length?`<div class="list">${entries.map(e=>`<div class="list-item clickable" data-time="${e.id}"><div class="main"><div class="title">${nlDate(entryDate(e))}</div><div class="sub">${esc(entryFrom(e))} - ${esc(entryTo(e))}${e.note?' · '+esc(e.note):''}</div></div><strong>${durationHM(entryMinutes(e))}</strong></div>`).join('')}</div>`:'<div class="empty">Nog geen uren.</div>'}`);
    $('#editThisJob').addEventListener('click',()=>{closeModal();editJob(id)});$('#hoursThisJob').addEventListener('click',()=>{closeModal();editTimeEntry(null,id)});$$('[data-time]').forEach(x=>x.addEventListener('click',()=>{closeModal();editTimeEntry(x.dataset.time)}));$$('[data-jobcheck]').forEach(c=>c.addEventListener('change',async()=>{j.checklistState=j.checklistState||{};j.checklistState[c.dataset.jobcheck]=c.checked;await JKDB.put('jobs',j)}));
  }

  async function renderGear(){
    title('Materiaal');
    $('#view').innerHTML=`<div class="tabs"><button class="tab ${state.gearTab==='mboxes'?'active':''}" data-gt="mboxes">Inpakchecklists</button><button class="tab ${state.gearTab==='tools'?'active':''}" data-gt="tools">Gereedschapregister</button></div><input class="search" id="gearSearch" placeholder="Zoek koffer, machine of onderdeel..."><div id="gearContent"></div>`;
    $$('[data-gt]').forEach(b=>b.addEventListener('click',()=>{state.gearTab=b.dataset.gt;renderGear()}));$('#gearSearch').addEventListener('input',renderGearContent);await renderGearContent();
  }
  async function renderGearContent(){
    const c=$('#gearContent');if(!c)return;const q=($('#gearSearch')?.value||'').toLowerCase();
    if(state.gearTab==='mboxes'){
      const rows=(await JKDB.all('mboxes')).filter(m=>(m.name+' '+m.type+' '+m.items.join(' ')).toLowerCase().includes(q));
      c.innerHTML=`<div class="successbox"><strong>Inpakken = afvinken</strong><br><span class="small">Open een Mbox, organizer of losse groep en vink af wat je hebt ingepakt. Met Reset maak je hem weer leeg voor de volgende klus.</span></div><div class="list">${rows.map(m=>{const done=m.items.filter(i=>m.checked?.[i]).length;return `<div class="list-item clickable" data-mbox="${m.id}"><div class="main"><div class="title">${esc(m.name)} · ${esc(m.type)}</div><div class="sub">${done}/${m.items.length} afgevinkt${m.notes?' · '+esc(m.notes):''}</div><div class="progress"><i style="width:${m.items.length?Math.round(done/m.items.length*100):0}%"></i></div></div><span>›</span></div>`}).join('')}</div>`;
      $$('[data-mbox]').forEach(x=>x.addEventListener('click',()=>showMboxChecklist(x.dataset.mbox)));
    }else{
      const boxes=await JKDB.all('mboxes'),map=Object.fromEntries(boxes.map(m=>[m.id,`${m.name} · ${m.type}`]));const rows=(await JKDB.all('tools')).filter(t=>(t.name+' '+t.category+' '+(map[t.location]||'')).toLowerCase().includes(q));
      c.innerHTML=`<div class="button-row"><button class="primary" id="addTool">+ Gereedschap</button></div><div class="list" style="margin-top:12px">${rows.map(t=>`<div class="list-item clickable" data-tool="${t.id}"><div class="main"><div class="title">${esc(t.name)}</div><div class="sub">${esc(t.category)} · ${esc(map[t.location]||'Los / vrij')}</div></div><span>›</span></div>`).join('')}</div>`;$('#addTool').addEventListener('click',()=>editTool());$$('[data-tool]').forEach(x=>x.addEventListener('click',()=>editTool(x.dataset.tool)));
    }
  }
  async function showMboxChecklist(id){
    const m=await JKDB.get('mboxes',id);m.checked=m.checked||{};const done=m.items.filter(i=>m.checked[i]).length;
    modal(`${modalHead(m.name+' · '+m.type)}${m.notes?`<div class="warning small">${esc(m.notes)}</div>`:''}<div class="check-card"><div class="check-summary"><strong>${done}/${m.items.length}</strong><span>afgevinkt</span></div>${m.items.map((item,i)=>`<label class="packing-row"><input type="checkbox" data-pack="${i}" ${m.checked[item]?'checked':''}><span>${esc(item)}</span></label>`).join('')}</div><div class="button-row" style="margin-top:12px"><button class="secondary" id="resetPack">Reset checklist</button><button class="secondary" id="editPack">Lijst bewerken</button></div>`);
    $$('[data-pack]').forEach(cb=>cb.addEventListener('change',async()=>{const item=m.items[Number(cb.dataset.pack)];m.checked[item]=cb.checked;await JKDB.put('mboxes',m);const n=m.items.filter(i=>m.checked[i]).length;const el=$('.check-summary strong');if(el)el.textContent=`${n}/${m.items.length}`;}));$('#resetPack').addEventListener('click',async()=>{if(confirm('Alle vinkjes van deze lijst wissen?')){m.checked={};await JKDB.put('mboxes',m);closeModal();showMboxChecklist(id)}});$('#editPack').addEventListener('click',()=>{closeModal();editMbox(id)});
  }
  async function editMbox(id){
    const m=id?await JKDB.get('mboxes',id):{id:JKDB.id('mbox'),name:'Mbox',type:'',items:[],notes:'',checked:{}};
    modal(`${modalHead(id?'Checklist bewerken':'Nieuwe checklist')}<form id="mboxForm"><div class="form-grid"><div class="field"><label>Naam</label><input name="name" value="${esc(m.name)}"></div><div class="field"><label>Type / inhoud</label><input name="type" value="${esc(m.type)}"></div><div class="field full"><label>Onderdelen - één per regel</label><textarea name="items" style="min-height:280px">${esc(m.items.join('\n'))}</textarea></div><div class="field full"><label>Notitie</label><textarea name="notes">${esc(m.notes||'')}</textarea></div></div><div class="button-row"><button class="primary">Opslaan</button>${id?'<button type="button" class="danger-btn" id="delMbox">Verwijderen</button>':''}</div></form>`);
    $('#mboxForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),items=String(f.get('items')).split('\n').map(x=>x.trim()).filter(Boolean),checked={};items.forEach(i=>{if(m.checked?.[i])checked[i]=true});Object.assign(m,{name:f.get('name'),type:f.get('type'),items,notes:f.get('notes'),checked,updatedAt:new Date().toISOString()});await JKDB.put('mboxes',m);closeModal();toast('Checklist opgeslagen');renderGearContent();});$('#delMbox')?.addEventListener('click',async()=>{if(confirm('Deze lijst verwijderen?')){await JKDB.remove('mboxes',id);closeModal();renderGearContent();}});
  }
  async function editTool(id){
    const t=id?await JKDB.get('tools',id):{id:JKDB.id('tool'),name:'',category:'',location:'',serial:'',purchaseDate:'',notes:''},boxes=await JKDB.all('mboxes');
    modal(`${modalHead(id?'Gereedschap bewerken':'Nieuw gereedschap')}<form id="toolForm"><div class="field"><label>Naam</label><input name="name" required value="${esc(t.name)}"></div><div class="form-grid"><div class="field"><label>Categorie</label><input name="category" value="${esc(t.category)}"></div><div class="field"><label>Locatie</label><select name="location"><option value="">Los / vrij</option>${boxes.map(m=>`<option value="${m.id}" ${m.id===t.location?'selected':''}>${esc(m.name+' · '+m.type)}</option>`).join('')}</select></div><div class="field"><label>Serienummer</label><input name="serial" value="${esc(t.serial||'')}"></div><div class="field"><label>Aanschafdatum</label><input type="date" name="purchaseDate" value="${esc(t.purchaseDate||'')}"></div><div class="field full"><label>Notities</label><textarea name="notes">${esc(t.notes||'')}</textarea></div></div><div class="button-row"><button class="primary">Opslaan</button>${id?'<button type="button" class="danger-btn" id="delTool">Verwijderen</button>':''}</div></form>`);
    $('#toolForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);['name','category','location','serial','purchaseDate','notes'].forEach(k=>t[k]=f.get(k));await JKDB.put('tools',t);closeModal();toast('Opgeslagen');renderGearContent();});$('#delTool')?.addEventListener('click',async()=>{if(confirm('Gereedschap verwijderen?')){await JKDB.remove('tools',id);closeModal();renderGearContent();}});
  }

  async function renderDocuments(){
    title('Documenten');const docs=await JKDB.all('documents');const counts={offerte:0,factuur:0,diversen:0};docs.forEach(d=>counts[docFolder(d)]++);
    const folderLabel=state.docFolder==='offerte'?'Offertes':state.docFolder==='factuur'?'Facturen':state.docFolder==='diversen'?'Diversen':'Documenten';
    $('#view').innerHTML=`<div class="button-row"><button class="primary" id="docQuote">+ Offerte</button><button class="primary" id="docInvoice">+ Factuur</button></div><div class="section-title"><h2>Mappen</h2></div><div class="folder-grid"><button class="folder ${state.docFolder==='offerte'?'active':''}" data-folder="offerte"><span>📁</span><strong>Offertes</strong><small>${counts.offerte} bestanden</small></button><button class="folder ${state.docFolder==='factuur'?'active':''}" data-folder="factuur"><span>📁</span><strong>Facturen</strong><small>${counts.factuur} bestanden</small></button><button class="folder ${state.docFolder==='diversen'?'active':''}" data-folder="diversen"><span>📁</span><strong>Diversen</strong><small>${counts.diversen} bestanden</small></button></div><div class="button-row" style="margin-top:12px"><button class="secondary" id="showAllDocs">Alle documenten</button><button class="secondary" id="importDocs">${state.docFolder==='all'?'PDF uploaden':`Upload naar ${folderLabel}`}</button></div><div id="docList"></div>`;
    $('#docQuote').addEventListener('click',()=>createBusinessDoc('Offerte'));$('#docInvoice').addEventListener('click',()=>createBusinessDoc('Factuur'));$$('[data-folder]').forEach(x=>x.addEventListener('click',()=>{state.docFolder=x.dataset.folder;renderDocuments()}));$('#showAllDocs').addEventListener('click',()=>{state.docFolder='all';renderDocuments()});$('#importDocs').addEventListener('click',()=>chooseImportFolder());renderDocumentList(docs);
  }
  function docFolder(d){const k=String(d.folder||d.kind||'').toLowerCase();return k.includes('offert')?'offerte':k.includes('fact')?'factuur':'diversen'}
  function docStatusHtml(d){const f=docFolder(d),m=d.meta||{};if(f==='factuur')return `<span class="status-chip ${m.sent?'on':''}">${m.sent?'✓ ':''}Verstuurd</span><span class="status-chip ${m.paid?'on':''}">${m.paid?'✓ ':''}Betaald</span>`;if(f==='offerte')return `<span class="status-chip ${m.sent?'on':''}">${m.sent?'✓ ':''}Verstuurd</span><span class="status-chip ${m.confirmed?'on':''}">${m.confirmed?'✓ ':''}Bevestigd</span>`;return ''}
  function renderDocumentList(docs){const c=$('#docList');if(!c)return;const filtered=docs.filter(d=>state.docFolder==='all'||docFolder(d)===state.docFolder).sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||''));c.innerHTML=`<div class="section-title"><h2>${state.docFolder==='all'?'Alle documenten':state.docFolder==='offerte'?'Offertes':state.docFolder==='factuur'?'Facturen':'Diversen'}</h2></div>${filtered.length?`<div class="list">${filtered.map(d=>`<div class="list-item clickable" data-doc="${d.id}"><div class="document-card"><div class="doc-icon">PDF</div><div class="main"><div class="title">${esc(d.filename)}</div><div class="sub">${fmtDateTime(d.createdAt)} · ${esc(d.kind||'PDF')}</div><div class="status-row">${docStatusHtml(d)}</div></div></div><span>›</span></div>`).join('')}</div>`:'<div class="empty">Deze map is nog leeg.</div>'}`;$$('[data-doc]').forEach(x=>x.addEventListener('click',()=>showDocument(x.dataset.doc)))}
  function chooseImportFolder(){
    if(state.docFolder!=='all'){state.importFolderTarget=state.docFolder;$('#hiddenExistingPdfInput').click();return;}
    modal(`${modalHead('PDF uploaden')}<p class="muted small">Kies in welke map je het bestand wilt plaatsen.</p><div class="grid two"><button class="quick" data-import-folder="offerte"><span class="emoji">📄</span><strong>Offertes</strong></button><button class="quick" data-import-folder="factuur"><span class="emoji">🧾</span><strong>Facturen</strong></button><button class="quick" data-import-folder="diversen"><span class="emoji">📁</span><strong>Diversen</strong></button></div>`);
    $$('[data-import-folder]').forEach(b=>b.addEventListener('click',()=>{state.importFolderTarget=b.dataset.importFolder;closeModal();$('#hiddenExistingPdfInput').click();}));
  }
  async function importExistingPdfs(files,folder='diversen'){let count=0;folder=['offerte','factuur','diversen'].includes(folder)?folder:'diversen';for(const file of files){if(!file.name.toLowerCase().endsWith('.pdf'))continue;await JKDB.put('documents',{id:JKDB.id('doc'),filename:file.name,kind:folder==='offerte'?'Offerte':folder==='factuur'?'Factuur':'Diversen',folder,blob:new Blob([await file.arrayBuffer()],{type:'application/pdf'}),createdAt:new Date().toISOString(),meta:{sent:false,paid:false,confirmed:false}});count++;}toast(`${count} PDF${count===1?'':'s'} geüpload naar ${folder==='offerte'?'Offertes':folder==='factuur'?'Facturen':'Diversen'}`);state.docFolder=folder;if(state.route==='documents')renderDocuments();}

  async function nextDocNumber(kind){
    const prefix=kind==='Factuur'?'FAC':'OFF',year=new Date().getFullYear(),docs=await JKDB.all('documents');let max=0;for(const d of docs){const n=d.meta?.number||d.number||d.filename||'',m=String(n).match(new RegExp(`${prefix}-${year}-(\\d+)`,'i'));if(m)max=Math.max(max,Number(m[1]));}return `${prefix}-${year}-${String(max+1).padStart(3,'0')}`;
  }
  async function createBusinessDoc(kind,prefill={}){
    const [clients,entries,company]=await Promise.all([JKDB.all('clients'),JKDB.all('timeEntries'),JKDB.get('settings','company')]);
    const number=await nextDocNumber(kind),isInvoice=kind==='Factuur',docDate=today(),deadline=addDays(docDate,isInvoice?14:30),lines=(prefill.lines||[]).slice(0,4);while(lines.length<4)lines.push({qty:'',description:'',price:''});
    const pClient=prefill.client||{};
    modal(`${modalHead('Nieuwe '+kind.toLowerCase())}<form id="businessDocForm"><div class="card form-section"><h3>Document</h3><div class="form-grid"><div class="field"><label>${kind}nummer</label><input name="number" required value="${esc(number)}"></div><div class="field"><label>${isInvoice?'Factuurdatum':'Datum'}</label><input type="date" name="docDate" value="${esc(docDate)}"></div><div class="field"><label>${isInvoice?'Datum werkzaamheden':'Werkzaamheden op'}</label><input name="workDate" placeholder="bijv. 04-10-2026" value="${esc(prefill.workDate||'')}"></div><div class="field"><label>${isInvoice?'Vervaldatum':'Geldig t/m'}</label><input type="date" name="deadline" value="${esc(deadline)}"></div></div></div>
      <div class="card form-section"><h3>Klant</h3><div class="field"><label>Kies bestaande klant</label><select id="clientPick"><option value="">Handmatig invullen</option>${clients.map(c=>`<option value="${c.id}" ${prefill.clientId===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Naam/bedrijf</label><input name="clientName" value="${esc(pClient.name||'')}"></div><div class="field"><label>T.a.v.</label><input name="attention" value="${esc(pClient.attention||'')}"></div><div class="field"><label>Adres</label><input name="address" value="${esc(pClient.address||'')}"></div><div class="field"><label>Postcode/Plaats</label><input name="postalCity" value="${esc(pClient.postalCity||'')}"></div></div>
      <div class="card form-section"><div class="section-inline"><h3>Werkzaamheden / materiaal</h3><span class="muted small">max. 4 regels in huidig sjabloon</span></div><div class="line-head"><span>Aantal</span><span>Omschrijving</span><span>Prijs p/st</span><span>Totaal</span></div>${lines.map((l,i)=>`<div class="invoice-line" data-line="${i}"><input inputmode="decimal" name="qty${i}" placeholder="1" value="${esc(l.qty||'')}"><input name="desc${i}" placeholder="Omschrijving" value="${esc(l.description||'')}"><input inputmode="decimal" name="price${i}" placeholder="0,00" value="${esc(l.price||'')}"><output id="lineTotal${i}">€ 0,00</output></div>`).join('')}<div class="doc-total"><span>Totaal te betalen</span><strong id="grandTotal">€ 0,00</strong></div></div>
      ${isInvoice&&entries.length?`<div class="card form-section"><div class="section-inline"><h3>Uren uit urenregistratie</h3><span class="muted small">optioneel</span></div><p class="muted small">Selecteer registraties. De app telt ze op en zet ze als één werkurenregel in de factuur.</p><div class="hours-select">${entries.sort((a,b)=>entryDate(b).localeCompare(entryDate(a))).slice(0,30).map(e=>`<label class="packing-row"><input type="checkbox" data-hour-entry="${e.id}"><span><strong>${nlDate(entryDate(e))}</strong> · ${esc(e.jobTitle||'Algemeen')} · ${durationHM(entryMinutes(e))} u</span></label>`).join('')}</div><div class="form-grid" style="margin-top:10px"><div class="field"><label>Uurtarief voor geselecteerde uren</label><input id="hourRate" inputmode="decimal" value="${esc(company?.defaultRate||'')}"></div><div class="field action-field"><button type="button" class="secondary" id="hoursToLine">Voeg geselecteerde uren toe</button></div></div></div>`:''}
      <div class="button-row"><button class="primary">Maak PDF</button><button type="button" class="secondary" data-close>Annuleren</button></div></form>`);

    function recalc(){let grand=0;for(let i=0;i<4;i++){const q=num($(`[name=qty${i}]`).value),p=num($(`[name=price${i}]`).value),t=q*p;grand+=t;$(`#lineTotal${i}`).textContent=money(t)}$('#grandTotal').textContent=money(grand);return grand}
    $$('[name^=qty], [name^=price]').forEach(x=>x.addEventListener('input',recalc));recalc();
    $('#clientPick').addEventListener('change',e=>{const c=clients.find(x=>x.id===e.target.value);if(!c)return;$('[name=clientName]').value=c.name||'';$('[name=attention]').value=c.attention||'';$('[name=address]').value=c.street||'';$('[name=postalCity]').value=[c.postal,c.city].filter(Boolean).join(' ')});
    if(prefill.clientId)$('#clientPick').dispatchEvent(new Event('change'));
    $('#hoursToLine')?.addEventListener('click',()=>{const ids=$$('[data-hour-entry]:checked').map(x=>x.dataset.hourEntry);if(!ids.length){alert('Selecteer eerst één of meer urenregistraties.');return}const selected=entries.filter(e=>ids.includes(e.id)),minutes=selected.reduce((s,e)=>s+entryMinutes(e),0),hours=Math.round(minutes/60*100)/100,rate=num($('#hourRate').value);let idx=0;for(let i=0;i<4;i++){if(!$(`[name=desc${i}]`).value.trim()){idx=i;break}}const dates=[...new Set(selected.map(entryDate))].sort(),jobs=[...new Set(selected.map(e=>e.jobTitle).filter(Boolean))];$(`[name=qty${idx}]`).value=String(hours).replace('.',',');$(`[name=desc${idx}]`).value=`Werkuren${jobs.length===1?' - '+jobs[0]:''}${dates.length===1?' ('+nlDate(dates[0])+')':dates.length>1?' ('+nlDate(dates[0])+' t/m '+nlDate(dates.at(-1))+')':''}`;$(`[name=price${idx}]`).value=rate?String(rate).replace('.',','):'';if(!$('[name=workDate]').value&&dates.length)$('[name=workDate]').value=dates.length===1?nlDate(dates[0]):`${nlDate(dates[0])} t/m ${nlDate(dates.at(-1))}`;recalc();toast('Uren toegevoegd aan regel');});
    $('#businessDocForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),items=[];for(let i=0;i<4;i++)items.push({qty:f.get(`qty${i}`),description:f.get(`desc${i}`),price:f.get(`price${i}`)});const data={kind,number:f.get('number'),docDate:f.get('docDate'),workDate:f.get('workDate'),deadline:f.get('deadline'),clientId:$('#clientPick').value,client:{name:f.get('clientName'),attention:f.get('attention'),address:f.get('address'),postalCity:f.get('postalCity')},lines:items,total:recalc()};try{const d=await generateBusinessPdf(data);closeModal();toast(kind+' opgeslagen');state.docFolder=isInvoice?'factuur':'offerte';await showDocument(d.id);if(state.route==='documents')renderDocuments();}catch(err){console.error(err);alert('PDF maken mislukt: '+err.message)}});
  }
  function setPdfText(form,name,value,size){try{const f=form.getTextField(name);f.setText(String(value??''));if(size)f.setFontSize(size);}catch(e){console.warn('PDF field',name,e.message)}}
  async function generateBusinessPdf(data){
    await ensurePdfLib();const isInvoice=data.kind==='Factuur',path=isInvoice?'templates/factuur-kor.pdf':'templates/offerte-kor.pdf',res=await fetch(path);if(!res.ok)throw new Error('PDF-sjabloon niet gevonden.');const pdf=await PDFLib.PDFDocument.load(await res.arrayBuffer()),form=pdf.getForm();
    setPdfText(form,isInvoice?'Factuurnummer':'Offertenummer',data.number,10);setPdfText(form,isInvoice?'Factuurdatum':'Datum',nlDate(data.docDate),10);setPdfText(form,isInvoice?'Datum werkzaamheden':'Werkzaamheden op',data.workDate||'',9);setPdfText(form,isInvoice?'Vervaldatum':'Geldig t/m',nlDate(data.deadline),10);setPdfText(form,'Naam/bedrijf',data.client.name,10);setPdfText(form,'T.a.v',data.client.attention,10);setPdfText(form,'Adres',data.client.address,10);setPdfText(form,'Postcode/Plaats',data.client.postalCity,10);
    let total=0;for(let i=0;i<4;i++){const l=data.lines[i]||{},q=num(l.qty),p=num(l.price),t=q*p;total+=t;setPdfText(form,`Aantal ${i+1}`,l.qty||'',9);setPdfText(form,`Omschrijving ${i+1}`,l.description||'',8);setPdfText(form,`Prijs ${i+1}`,l.price?moneyNumber(p):'',9);setPdfText(form,`Totaal ${i+1}`,(l.qty||l.description||l.price)?moneyNumber(t):'',9);}setPdfText(form,'Totaal te betalen EUR',moneyNumber(total),10);
    try{form.updateFieldAppearances();form.flatten();}catch(e){console.warn('Flatten',e)}
    const bytes=await pdf.save(),blob=new Blob([bytes],{type:'application/pdf'}),filename=`${data.number}.pdf`,folder=isInvoice?'factuur':'offerte',doc={id:JKDB.id('doc'),filename,kind:data.kind,folder,blob,createdAt:new Date().toISOString(),meta:{...data,total,lines:data.lines,sent:false,paid:false,confirmed:false}};await JKDB.put('documents',doc);return doc;
  }
  function moneyNumber(v){return Number(v||0).toFixed(2).replace('.',',')}
  async function showDocument(id){
    const d=await JKDB.get('documents',id),folder=docFolder(d),m=d.meta||{};
    const statusBox=folder==='factuur'?`<div class="card" style="margin-top:12px"><h3>Status factuur</h3><label class="checkline"><input type="checkbox" id="docSent" ${m.sent?'checked':''}><span>Verstuurd</span></label><label class="checkline"><input type="checkbox" id="docPaid" ${m.paid?'checked':''}><span>Betaald</span></label></div>`:folder==='offerte'?`<div class="card" style="margin-top:12px"><h3>Status offerte</h3><label class="checkline"><input type="checkbox" id="docSent" ${m.sent?'checked':''}><span>Verstuurd</span></label><label class="checkline"><input type="checkbox" id="docConfirmed" ${m.confirmed?'checked':''}><span>Bevestigd</span></label></div>`:'';
    modal(`${modalHead(d.filename)}<div class="card"><div class="document-card"><div class="doc-icon">PDF</div><div><h3>${esc(d.filename)}</h3><div class="muted small">${esc(d.kind||'PDF')} · ${fmtDateTime(d.createdAt)}</div>${d.meta?.total!=null?`<div class="big-number" style="margin-top:8px">${money(d.meta.total)}</div>`:''}</div></div><div class="button-row" style="margin-top:14px"><button class="primary" id="shareDoc">Delen / bewaar in iCloud</button><button class="secondary" id="downloadDoc">Download</button></div>${folder==='offerte'&&d.meta?.lines?`<button class="secondary" id="quoteToInvoice" style="width:100%;margin-top:10px">Zet offerte om naar factuur</button>`:''}</div>${statusBox}<div class="card" style="margin-top:12px"><h3>Map</h3><div class="field"><label>Verplaats document naar</label><select id="moveDocFolder"><option value="offerte" ${folder==='offerte'?'selected':''}>Offertes</option><option value="factuur" ${folder==='factuur'?'selected':''}>Facturen</option><option value="diversen" ${folder==='diversen'?'selected':''}>Diversen</option></select></div></div><button class="danger-btn" id="delDoc" style="width:100%">Uit app verwijderen</button>`);
    $('#shareDoc').addEventListener('click',()=>shareBlob(d.blob,d.filename));$('#downloadDoc').addEventListener('click',()=>downloadBlob(d.blob,d.filename));$('#quoteToInvoice')?.addEventListener('click',()=>{const meta=d.meta;closeModal();createBusinessDoc('Factuur',{clientId:meta.clientId,client:meta.client,lines:meta.lines,workDate:meta.workDate})});
    const saveStatus=async()=>{d.meta=d.meta||{};if($('#docSent'))d.meta.sent=$('#docSent').checked;if($('#docPaid'))d.meta.paid=$('#docPaid').checked;if($('#docConfirmed'))d.meta.confirmed=$('#docConfirmed').checked;await JKDB.put('documents',d);toast('Status opgeslagen');};
    $('#docSent')?.addEventListener('change',saveStatus);$('#docPaid')?.addEventListener('change',saveStatus);$('#docConfirmed')?.addEventListener('change',saveStatus);
    $('#moveDocFolder').addEventListener('change',async e=>{const target=e.target.value;d.folder=target;d.kind=target==='offerte'?'Offerte':target==='factuur'?'Factuur':'Diversen';d.meta=d.meta||{};if(target!=='factuur')d.meta.paid=false;if(target!=='offerte')d.meta.confirmed=false;await JKDB.put('documents',d);toast('Document verplaatst');closeModal();state.docFolder=target;if(state.route==='documents')renderDocuments();});
    $('#delDoc').addEventListener('click',async()=>{if(confirm('Deze PDF uit de app verwijderen?')){await JKDB.remove('documents',id);closeModal();if(state.route==='documents')renderDocuments();}});
  }
  async function shareBlob(blob,filename){const file=new File([blob],filename,{type:blob.type||'application/pdf'});try{if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({files:[file]});return}}catch(e){if(e.name==='AbortError')return}downloadBlob(blob,filename)}
  function downloadBlob(blob,filename){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;document.body.appendChild(a);a.click();const u=a.href;a.remove();setTimeout(()=>URL.revokeObjectURL(u),2000)}

  async function renderMore(){
    title('Meer');const [checks,clients,entries,company,backup,cloudStatus]=await Promise.all([JKDB.all('checklists'),JKDB.all('clients'),JKDB.all('timeEntries'),JKDB.get('settings','company'),JKDB.get('settings','backup'),JKDB.get('settings','cloudStatus')]);const cs=JKCloud.status();
    $('#view').innerHTML=`<div class="list"><div class="list-item clickable" id="cloudMenu"><div class="main"><div class="title">☁️ Synchronisatie</div><div class="sub">${cs.signedIn?(cs.email+' · '+(cloudStatus?.lastSync?'laatst '+fmtDateTime(cloudStatus.lastSync):'nog niet gesynchroniseerd')):'Niet ingelogd'}</div></div><span>›</span></div><div class="list-item clickable" id="timeMenu"><div class="main"><div class="title">🕒 Urenregistratie</div><div class="sub">${entries.length} registraties · handmatig van-tot</div></div><span>›</span></div><div class="list-item clickable" id="checkMenu"><div class="main"><div class="title">✅ Algemene checklists</div><div class="sub">${checks.length} lijsten</div></div><span>›</span></div><div class="list-item clickable" id="clientMenu"><div class="main"><div class="title">👥 Klanten</div><div class="sub">${clients.length} klanten</div></div><span>›</span></div><div class="list-item clickable" id="companyMenu"><div class="main"><div class="title">🏢 Bedrijfsgegevens</div><div class="sub">${esc(company?.companyName||'JK Works Dordrecht')}</div></div><span>›</span></div><div class="list-item clickable" id="backupMenu"><div class="main"><div class="title">☁️ Back-up & herstel</div><div class="sub">${backup?.lastBackup?'Laatst '+fmtDateTime(backup.lastBackup):'Nog geen back-up'}</div></div><span>›</span></div><div class="list-item clickable" id="installMenu"><div class="main"><div class="title">📱 Installatie & iCloud</div><div class="sub">iPhone, GitHub Pages en opslaan in Bestanden</div></div><span>›</span></div></div>`;
    $('#cloudMenu').addEventListener('click',showCloud);$('#timeMenu').addEventListener('click',showTimeEntries);$('#checkMenu').addEventListener('click',showChecklists);$('#clientMenu').addEventListener('click',showClients);$('#companyMenu').addEventListener('click',showCompany);$('#backupMenu').addEventListener('click',showBackup);$('#installMenu').addEventListener('click',showInstallInfo);
  }

  function showCloud(){
    const cs=JKCloud.status();
    if(cs.signedIn){
      modal(`${modalHead('Synchronisatie')}<div class="card"><h3>Ingelogd</h3><p class="small"><strong>${esc(cs.email)}</strong></p><p class="muted small">Wijzigingen worden lokaal opgeslagen en, zodra internet beschikbaar is, naar Supabase gesynchroniseerd. Dezelfde login op iPhone en Mac gebruikt dezelfde gegevens.</p><div class="button-row"><button class="primary" id="syncNow">Nu synchroniseren</button><button class="secondary" id="cloudLogout">Uitloggen</button></div></div>`);
      $('#syncNow').addEventListener('click',async()=>{try{await JKCloud.syncNow();toast('Synchronisatie voltooid');closeModal();render();}catch(e){alert('Synchroniseren mislukt: '+e.message)}});
      $('#cloudLogout').addEventListener('click',async()=>{await JKCloud.signOut();closeModal();toast('Uitgelogd');render();});
    } else {
      modal(`${modalHead('Synchronisatie')}<div class="card"><h3>Inloggen</h3><p class="muted small">Gebruik op je iPhone en MacBook hetzelfde e-mailadres en wachtwoord.</p><form id="cloudForm"><div class="field"><label>E-mail</label><input type="email" name="email" required autocomplete="email"></div><div class="field"><label>Wachtwoord</label><input type="password" name="password" required minlength="6" autocomplete="current-password"></div><div class="button-row"><button class="primary" name="action" value="signin">Inloggen</button><button class="secondary" name="action" value="signup">Account maken</button></div></form></div>`);
      $('#cloudForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),action=e.submitter?.value||'signin';try{if(action==='signup'){const r=await JKCloud.signUp(f.get('email'),f.get('password'));if(!r.session){alert('Account gemaakt. Controleer je e-mail voor de bevestigingslink en log daarna in.');return;}}else await JKCloud.signIn(f.get('email'),f.get('password'));closeModal();toast('Cloud gekoppeld');render();}catch(err){alert((action==='signup'?'Account maken':'Inloggen')+' mislukt: '+err.message)}});
    }
  }

  async function showTimeEntries(){
    const es=(await JKDB.all('timeEntries')).sort((a,b)=>(entryDate(b)+entryFrom(b)).localeCompare(entryDate(a)+entryFrom(a)));
    modal(`${modalHead('Urenregistratie')}<button class="primary" id="addTime" style="width:100%;margin-bottom:12px">+ Uren toevoegen</button>${es.length?`<div class="list">${es.map(e=>`<div class="list-item clickable" data-time="${e.id}"><div class="main"><div class="title">${nlDate(entryDate(e))} · ${esc(e.jobTitle||'Algemeen')}</div><div class="sub">${esc(entryFrom(e))} - ${esc(entryTo(e))}${e.note?' · '+esc(e.note):''}</div></div><strong>${durationHM(entryMinutes(e))}</strong></div>`).join('')}</div>`:'<div class="empty">Nog geen uren geregistreerd.</div>'}`);$('#addTime').addEventListener('click',()=>{closeModal();editTimeEntry()});$$('[data-time]').forEach(x=>x.addEventListener('click',()=>{closeModal();editTimeEntry(x.dataset.time)}));
  }
  async function editTimeEntry(id,jobId=''){
    const jobs=(await JKDB.all('jobs')).sort((a,b)=>(b.date||'').localeCompare(a.date||'')),old=id?await JKDB.get('timeEntries',id):null,e=old||{id:JKDB.id('time'),jobId,jobTitle:'',date:today(),from:'08:00',to:'16:30',note:''};
    if(old&&!e.date&&e.start){e.date=entryDate(e);e.from=entryFrom(e);e.to=entryTo(e)}
    modal(`${modalHead(id?'Uren bewerken':'Uren toevoegen')}<form id="timeForm"><div class="field"><label>Klus</label><select name="jobId"><option value="">Algemene werkzaamheden</option>${jobs.map(j=>`<option value="${j.id}" ${j.id===e.jobId?'selected':''}>${esc(j.title)}${j.clientName?' · '+esc(j.clientName):''}</option>`).join('')}</select></div><div class="field"><label>Datum</label><input type="date" name="date" required value="${esc(e.date||today())}"></div><div class="form-grid"><div class="field"><label>Van</label><input type="time" name="from" required value="${esc(e.from||'')}"></div><div class="field"><label>Tot</label><input type="time" name="to" required value="${esc(e.to||'')}"></div></div><div class="field"><label>Notitie</label><input name="note" value="${esc(e.note||'')}" placeholder="Optioneel"></div><div class="card small" id="timePreview"></div><div class="button-row"><button class="primary">Opslaan</button>${id?'<button type="button" class="danger-btn" id="delTime">Verwijderen</button>':''}</div></form>`);
    const preview=()=>{const f=new FormData($('#timeForm')),tmp={date:f.get('date'),from:f.get('from'),to:f.get('to')};$('#timePreview').innerHTML=`Tijdsduur: <strong>${durationHM(entryMinutes(tmp))} uur</strong>`};$$('#timeForm input').forEach(x=>x.addEventListener('input',preview));preview();$('#timeForm').addEventListener('submit',async ev=>{ev.preventDefault();const f=new FormData(ev.target),j=jobs.find(x=>x.id===f.get('jobId'));Object.assign(e,{jobId:j?.id||'',jobTitle:j?.title||'Algemene werkzaamheden',date:f.get('date'),from:f.get('from'),to:f.get('to'),note:f.get('note'),start:null,end:null});await JKDB.put('timeEntries',e);closeModal();toast('Uren opgeslagen');if(state.route==='dashboard')render();else showTimeEntries();});$('#delTime')?.addEventListener('click',async()=>{if(confirm('Deze urenregistratie verwijderen?')){await JKDB.remove('timeEntries',id);closeModal();showTimeEntries();}});
  }

  async function showClients(){const cs=(await JKDB.all('clients')).sort((a,b)=>a.name.localeCompare(b.name));modal(`${modalHead('Klanten')}<button class="primary" id="addClient" style="width:100%;margin-bottom:12px">+ Nieuwe klant</button>${cs.length?`<div class="list">${cs.map(c=>`<div class="list-item clickable" data-client="${c.id}"><div class="main"><div class="title">${esc(c.name)}</div><div class="sub">${esc([c.city,c.phone].filter(Boolean).join(' · ')||'Geen extra gegevens')}</div></div><span>›</span></div>`).join('')}</div>`:'<div class="empty">Nog geen klanten.</div>'}`);$('#addClient').addEventListener('click',()=>{closeModal();editClient()});$$('[data-client]').forEach(x=>x.addEventListener('click',()=>{closeModal();editClient(x.dataset.client)}));}
  async function editClient(id){const c=id?await JKDB.get('clients',id):{id:JKDB.id('client'),name:'',attention:'',street:'',postal:'',city:'',phone:'',email:'',notes:''};modal(`${modalHead(id?'Klant bewerken':'Nieuwe klant')}<form id="clientForm"><div class="field"><label>Naam/bedrijf</label><input name="name" required value="${esc(c.name)}"></div><div class="field"><label>T.a.v.</label><input name="attention" value="${esc(c.attention||'')}"></div><div class="field"><label>Adres</label><input name="street" value="${esc(c.street||'')}"></div><div class="form-grid"><div class="field"><label>Postcode</label><input name="postal" value="${esc(c.postal||'')}"></div><div class="field"><label>Plaats</label><input name="city" value="${esc(c.city||'')}"></div><div class="field"><label>Telefoon</label><input name="phone" value="${esc(c.phone||'')}"></div><div class="field"><label>E-mail</label><input type="email" name="email" value="${esc(c.email||'')}"></div><div class="field full"><label>Notities</label><textarea name="notes">${esc(c.notes||'')}</textarea></div></div><div class="button-row"><button class="primary">Opslaan</button>${id?'<button type="button" class="danger-btn" id="delClient">Verwijderen</button>':''}</div></form>`);$('#clientForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);['name','attention','street','postal','city','phone','email','notes'].forEach(k=>c[k]=f.get(k));await JKDB.put('clients',c);closeModal();toast('Klant opgeslagen');if(state.route==='more')render();});$('#delClient')?.addEventListener('click',async()=>{if(confirm('Klant verwijderen?')){await JKDB.remove('clients',id);closeModal();}});}
  async function showChecklists(){const cs=await JKDB.all('checklists');modal(`${modalHead('Algemene checklists')}<button class="primary" id="addCheck" style="width:100%;margin-bottom:12px">+ Nieuwe checklist</button><div class="list">${cs.map(c=>`<div class="list-item clickable" data-checklist="${c.id}"><div class="main"><div class="title">${esc(c.name)}</div><div class="sub">${c.items.length} punten</div></div><span>›</span></div>`).join('')}</div>`);$('#addCheck').addEventListener('click',()=>{closeModal();editChecklist()});$$('[data-checklist]').forEach(x=>x.addEventListener('click',()=>{closeModal();editChecklist(x.dataset.checklist)}));}
  async function editChecklist(id){const c=id?await JKDB.get('checklists',id):{id:JKDB.id('check'),name:'',items:[]};modal(`${modalHead(id?'Checklist bewerken':'Nieuwe checklist')}<form id="checkForm"><div class="field"><label>Naam</label><input name="name" required value="${esc(c.name)}"></div><div class="field"><label>Punten - één per regel</label><textarea name="items" style="min-height:260px">${esc(c.items.join('\n'))}</textarea></div><div class="button-row"><button class="primary">Opslaan</button>${id?'<button type="button" class="danger-btn" id="delCheck">Verwijderen</button>':''}</div></form>`);$('#checkForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);c.name=f.get('name');c.items=String(f.get('items')).split('\n').map(x=>x.trim()).filter(Boolean);await JKDB.put('checklists',c);closeModal();toast('Checklist opgeslagen')});$('#delCheck')?.addEventListener('click',async()=>{if(confirm('Checklist verwijderen?')){await JKDB.remove('checklists',id);closeModal();}})}
  async function showCompany(){const c=await JKDB.get('settings','company');modal(`${modalHead('Bedrijfsgegevens')}<form id="companyForm"><div class="field"><label>Bedrijfsnaam</label><input name="companyName" value="${esc(c.companyName||'')}"></div><div class="field"><label>Naam</label><input name="owner" value="${esc(c.owner||'')}"></div><label class="checkline"><input type="checkbox" name="kor" ${c.kor?'checked':''}><span>Kleineondernemersregeling (KOR) actief</span></label><div class="field"><label>KOR sinds</label><input type="date" name="korSince" value="${esc(c.korSince||'')}"></div><div class="field"><label>Standaard uurtarief voor facturen</label><input type="number" step="0.01" name="defaultRate" value="${esc(c.defaultRate||'')}"></div><div class="field"><label>Notities</label><textarea name="notes">${esc(c.notes||'')}</textarea></div><button class="primary" style="width:100%">Opslaan</button></form>`);$('#companyForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);Object.assign(c,{companyName:f.get('companyName'),owner:f.get('owner'),kor:f.get('kor')==='on',korSince:f.get('korSince'),defaultRate:f.get('defaultRate'),notes:f.get('notes')});await JKDB.put('settings',c);closeModal();toast('Bedrijfsgegevens opgeslagen');});}

  function showBackup(){modal(`${modalHead('Back-up & herstel')}<div class="card"><h3>iCloud-back-up maken</h3><p class="muted small">Maakt één bestand met klanten, uren, checklists en alle PDF's. Bewaar dat via de deelkaart in iCloud Drive.</p><button class="primary" id="exportBackup" style="width:100%">Maak volledige back-up</button></div><div class="card"><h3>Back-up terugzetten</h3><p class="muted small">Dit vervangt de huidige lokale appgegevens.</p><button class="secondary" id="importBackup" style="width:100%">Kies back-upbestand</button></div>`);$('#exportBackup').addEventListener('click',exportBackup);$('#importBackup').addEventListener('click',()=>$('#hiddenBackupInput').click())}
  async function blobToDataURL(blob){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(blob)})}
  async function serializeRecord(r){const o={...r};for(const k of Object.keys(o))if(o[k] instanceof Blob)o[k]={__blob:true,type:o[k].type,data:await blobToDataURL(o[k])};return o}
  function dataURLToBlob(url){const [meta,b64]=url.split(','),mime=/data:(.*?);base64/.exec(meta)?.[1]||'application/octet-stream',bin=atob(b64),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return new Blob([a],{type:mime})}
  async function exportBackup(){try{const payload={format:'JKWORKS_BACKUP_V2',createdAt:new Date().toISOString(),stores:{}};for(const s of JKDB.stores){payload.stores[s]=[];for(const r of await JKDB.all(s))payload.stores[s].push(await serializeRecord(r))}const blob=new Blob([JSON.stringify(payload)],{type:'application/json'}),name=`JK-Works-backup-${today()}.jkbackup.json`;await JKDB.put('settings',{id:'backup',lastBackup:new Date().toISOString()});closeModal();await shareBlob(blob,name);toast('Back-up gemaakt');if(state.route==='dashboard')render();}catch(e){alert('Back-up maken lukte niet: '+e.message)}}
  async function restoreBackup(file){try{const p=JSON.parse(await file.text());if(!['JKWORKS_BACKUP_V1','JKWORKS_BACKUP_V2'].includes(p.format))throw new Error('Onbekend back-upformaat');if(!confirm('Huidige appgegevens vervangen door deze back-up?'))return;for(const s of JKDB.stores){await JKDB.clear(s);for(const rec of (p.stores[s]||[])){for(const k of Object.keys(rec))if(rec[k]?.__blob)rec[k]=dataURLToBlob(rec[k].data);await JKDB.put(s,rec)}}await JKDB.put('settings',{id:'backup',lastBackup:new Date().toISOString()});await JKDB.put('settings',{id:'seedVersion',value:3,at:new Date().toISOString()});toast('Back-up teruggezet');go('dashboard')}catch(e){alert('Terugzetten mislukt: '+e.message)}}
  function showInstallInfo(){modal(`${modalHead('Installatie & iCloud')}<div class="card"><h3>Op iPhone</h3><p class="small">Open je GitHub Pages-link in Safari → Deel → <strong>Zet op beginscherm</strong>. Daarna opent JK Works als app.</p></div><div class="card"><h3>Offertes en facturen</h3><p class="small">De app maakt de PDF op je iPhone. Kies daarna <strong>Delen / bewaar in iCloud</strong> → <strong>Bewaar in Bestanden</strong> → jouw map in iCloud Drive.</p></div><div class="card"><h3>Update vanaf GitHub</h3><p class="small">Vervang op GitHub de oude appbestanden door deze nieuwe versie. De lokale gegevens blijven in dezelfde browserdatabase staan. Maak voor de zekerheid eerst een back-up.</p></div>`)}
  async function quickAdd(){modal(`${modalHead('Snel toevoegen')}<div class="grid two"><button class="quick" id="qaInvoice"><span class="emoji">🧾</span><strong>Factuur</strong></button><button class="quick" id="qaQuote"><span class="emoji">📄</span><strong>Offerte</strong></button><button class="quick" id="qaTime"><span class="emoji">🕒</span><strong>Uren</strong></button><button class="quick" id="qaJob"><span class="emoji">👷</span><strong>Klus</strong></button></div>`);$('#qaInvoice').addEventListener('click',()=>{closeModal();createBusinessDoc('Factuur')});$('#qaQuote').addEventListener('click',()=>{closeModal();createBusinessDoc('Offerte')});$('#qaTime').addEventListener('click',()=>{closeModal();editTimeEntry()});$('#qaJob').addEventListener('click',()=>{closeModal();editJob()});}

  return {init,go};
})();
document.addEventListener('DOMContentLoaded',()=>App.init());
