/* JK Works Dordrecht - persoonlijke PWA */
const App = (() => {
  const state = { route:'dashboard', gearTab:'mboxes', docTab:'templates', timerTick:null, pdfLibPromise:null };
  const PDFLIB_URL='https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/dist/pdf-lib.min.js';
  const $ = (s,r=document)=>r.querySelector(s);
  const $$ = (s,r=document)=>[...r.querySelectorAll(s)];
  const esc = (v='') => String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const fmtDate = v => v ? new Intl.DateTimeFormat('nl-NL',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(v)) : '—';
  const fmtDateTime = v => v ? new Intl.DateTimeFormat('nl-NL',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v)) : '—';
  const money = v => new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(Number(v||0));
  const duration = ms => { ms=Math.max(0,ms); const h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000),s=Math.floor(ms%60000/1000); return [h,m,s].map(x=>String(x).padStart(2,'0')).join(':'); };

  async function init(){
    await JKDB.open(); await JKDB.seed();
    bindNav(); bindGlobalInputs(); registerSW(); await render();
    if(navigator.onLine) setTimeout(()=>ensurePdfLib().catch(()=>{}),1200);
  }
  function registerSW(){ if('serviceWorker' in navigator && location.protocol.startsWith('http')) navigator.serviceWorker.register('./service-worker.js').catch(()=>{}); }
  function ensurePdfLib(){
    if(window.PDFLib) return Promise.resolve(window.PDFLib);
    if(state.pdfLibPromise) return state.pdfLibPromise;
    state.pdfLibPromise=new Promise((resolve,reject)=>{
      const sc=document.createElement('script'); sc.src=PDFLIB_URL; sc.async=true; sc.crossOrigin='anonymous';
      const timer=setTimeout(()=>{sc.remove();state.pdfLibPromise=null;reject(new Error('PDF-module kon niet worden geladen. Controleer je internetverbinding en probeer opnieuw.'));},15000);
      sc.onload=()=>{clearTimeout(timer); if(window.PDFLib)resolve(window.PDFLib); else {state.pdfLibPromise=null;reject(new Error('PDF-module is niet beschikbaar.'));}};
      sc.onerror=()=>{clearTimeout(timer);state.pdfLibPromise=null;reject(new Error('PDF-module kon niet worden geladen. Open de app één keer met internet.'));};
      document.head.appendChild(sc);
    });
    return state.pdfLibPromise;
  }

  function bindNav(){
    $$('.nav-item').forEach(b=>b.addEventListener('click',()=>go(b.dataset.route)));
    $('#quickAddBtn').addEventListener('click',quickAdd);
  }
  function bindGlobalInputs(){
    $('#hiddenPdfInput').addEventListener('change', async e=>{const f=e.target.files[0]; if(f) await importPdfTemplate(f); e.target.value='';});
    $('#hiddenExistingPdfInput').addEventListener('change', async e=>{const files=[...e.target.files]; if(files.length) await importExistingPdfs(files); e.target.value='';});
    $('#hiddenBackupInput').addEventListener('change', async e=>{const f=e.target.files[0]; if(f) await restoreBackup(f); e.target.value='';});
  }
  async function go(route){ state.route=route; $$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===route)); await render(); window.scrollTo({top:0,behavior:'instant'}); }
  function title(t){$('#pageTitle').textContent=t;}
  function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2200)}
  function modal(html){$('#modalRoot').innerHTML=`<div class="modal-backdrop"><section class="modal">${html}</section></div>`; $('.modal-backdrop').addEventListener('click',e=>{if(e.target.classList.contains('modal-backdrop'))closeModal()});$$('[data-close]').forEach(x=>x.addEventListener('click',closeModal));}
  function closeModal(){ $('#modalRoot').innerHTML=''; }
  function modalHead(t){return `<div class="modal-head"><h2>${esc(t)}</h2><button class="close-btn" data-close>×</button></div>`}

  async function render(){ clearInterval(state.timerTick); state.timerTick=null; const v=$('#view'); v.innerHTML='<div class="empty">Laden…</div>';
    try{
      if(state.route==='dashboard') return renderDashboard();
      if(state.route==='jobs') return renderJobs();
      if(state.route==='gear') return renderGear();
      if(state.route==='documents') return renderDocuments();
      if(state.route==='more') return renderMore();
    }catch(e){ console.error(e); v.innerHTML=`<div class="card"><h2>Er ging iets mis</h2><p class="muted">${esc(e.message||e)}</p></div>`; }
  }

  async function renderDashboard(){
    title('Dashboard');
    const [jobs,docs,tools,backup,entries]=await Promise.all([JKDB.all('jobs'),JKDB.all('documents'),JKDB.all('tools'),JKDB.get('settings','backup'),JKDB.all('timeEntries')]);
    const active=jobs.filter(j=>j.status!=='afgerond').length, month=new Date().toISOString().slice(0,7), monthHours=entries.filter(e=>e.start?.startsWith(month)).reduce((s,e)=>s+entryMs(e),0)/3600000;
    const run=entries.find(e=>!e.end);
    const daysSinceBackup=backup?.lastBackup?Math.floor((Date.now()-new Date(backup.lastBackup))/86400000):999;
    $('#view').innerHTML=`
      ${daysSinceBackup>7?`<div class="warning"><strong>Back-up aanbevolen</strong><br><span class="small">Je laatste iCloud-back-up is ${backup?.lastBackup?daysSinceBackup+' dagen geleden':'nog niet gemaakt'}.</span> <button class="link-btn" id="dashBackup">Nu maken</button></div>`:''}
      <div class="hero"><div class="muted small">Persoonlijke bedrijfsapp</div><h2>JK Works Dordrecht</h2><div class="small">Klussen, materiaal, uren en documenten op één plek.</div></div>
      ${run?`<div class="card"><div class="metric-label">LOPENDE TIJDREGISTRATIE</div><div class="timer" id="dashTimer">${duration(Date.now()-new Date(run.start))}</div><div class="muted small">${esc(run.jobTitle||'Algemene werkzaamheden')}</div><div class="button-row" style="margin-top:12px"><button class="danger-btn" id="stopTimer">Stop timer</button></div></div>`:''}
      <div class="kpi-row">
        <div class="kpi"><strong>${active}</strong><span>OPEN KLUSSEN</span></div>
        <div class="kpi"><strong>${docs.length}</strong><span>PDF'S</span></div>
        <div class="kpi"><strong>${monthHours.toFixed(1).replace('.',',')}</strong><span>UREN DEZE MAAND</span></div>
      </div>
      <div class="section-title"><h2>Snel openen</h2></div>
      <div class="quick-grid">
        <button class="quick" data-go="jobs"><span class="emoji">👷</span><strong>Klussen</strong></button>
        <button class="quick" data-go="gear"><span class="emoji">🧰</span><strong>Mboxen & gereedschap</strong></button>
        <button class="quick" data-go="documents"><span class="emoji">📄</span><strong>Offertes & facturen</strong></button>
        <button class="quick" id="startTime"><span class="emoji">⏱</span><strong>${run?'Timer bekijken':'Uren starten'}</strong></button>
      </div>
      <div class="section-title"><h2>Materiaal</h2><button class="link-btn" data-go="gear">Alles</button></div>
      <div class="card"><div class="big-number">${tools.length}</div><div class="muted small">gereedschappen en accu's geregistreerd</div></div>`;
    $$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
    $('#startTime').addEventListener('click',()=>run?showTimeEntries():startTimerModal());
    $('#dashBackup')?.addEventListener('click',exportBackup);
    if(run){ $('#stopTimer').addEventListener('click',()=>stopTimer(run.id)); state.timerTick=setInterval(()=>{const el=$('#dashTimer'); if(el)el.textContent=duration(Date.now()-new Date(run.start));},1000); }
  }
  function entryMs(e){return (e.end?new Date(e.end):new Date())-new Date(e.start)}

  async function renderJobs(){
    title('Klussen'); const jobs=(await JKDB.all('jobs')).sort((a,b)=>(b.date||'').localeCompare(a.date||''));
    $('#view').innerHTML=`<div class="button-row"><button class="primary" id="newJob">+ Nieuwe klus</button><button class="secondary" id="clientsBtn">Klanten</button></div>
      <div class="section-title"><h2>Alle klussen</h2></div><div class="list" id="jobList">${jobs.length?jobs.map(jobRow).join(''):'<div class="empty">Nog geen klussen. Voeg je eerste klus toe.</div>'}</div>`;
    $('#newJob').addEventListener('click',()=>editJob()); $('#clientsBtn').addEventListener('click',showClients); $$('[data-job]').forEach(x=>x.addEventListener('click',()=>showJob(x.dataset.job)));
  }
  function jobRow(j){const cls=j.status==='afgerond'?'success':j.status==='gepland'?'warn':'';return `<div class="list-item" data-job="${esc(j.id)}"><div class="main"><div class="title">${esc(j.title||'Klus')}</div><div class="sub">${esc(j.clientName||'Geen klant')} · ${fmtDate(j.date)}</div></div><span class="pill ${cls}">${esc(j.status||'open')}</span></div>`}
  async function editJob(id){
    const j=id?await JKDB.get('jobs',id):{id:JKDB.id('job'),title:'',clientId:'',clientName:'',date:new Date().toISOString().slice(0,10),address:'',status:'gepland',notes:'',checklistId:'c_general',checklistState:{}};
    const [clients,checks]=await Promise.all([JKDB.all('clients'),JKDB.all('checklists')]);
    modal(`${modalHead(id?'Klus bewerken':'Nieuwe klus')}<form id="jobForm" class="form-grid">
      <div class="field full"><label>Omschrijving</label><input name="title" required value="${esc(j.title)}" placeholder="Bijv. plinten afkitten" /></div>
      <div class="field"><label>Klant</label><select name="clientId"><option value="">— geen —</option>${clients.map(c=>`<option value="${esc(c.id)}" ${c.id===j.clientId?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div>
      <div class="field"><label>Datum</label><input name="date" type="date" value="${esc(j.date)}" /></div>
      <div class="field full"><label>Adres</label><input name="address" value="${esc(j.address)}" /></div>
      <div class="field"><label>Status</label><select name="status">${['gepland','bezig','wachten','afgerond'].map(s=>`<option ${s===j.status?'selected':''}>${s}</option>`).join('')}</select></div>
      <div class="field"><label>Checklist</label><select name="checklistId"><option value="">— geen —</option>${checks.map(c=>`<option value="${c.id}" ${c.id===j.checklistId?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div>
      <div class="field full"><label>Notities</label><textarea name="notes">${esc(j.notes)}</textarea></div>
      <div class="button-row full"><button type="submit" class="primary">Opslaan</button>${id?'<button type="button" class="danger-btn" id="deleteJob">Verwijderen</button>':''}</div></form>`);
    $('#jobForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),client=clients.find(c=>c.id===f.get('clientId'));Object.assign(j,{title:f.get('title'),clientId:f.get('clientId'),clientName:client?.name||'',date:f.get('date'),address:f.get('address'),status:f.get('status'),checklistId:f.get('checklistId'),notes:f.get('notes'),updatedAt:new Date().toISOString()});await JKDB.put('jobs',j);closeModal();toast('Klus opgeslagen');render();});
    $('#deleteJob')?.addEventListener('click',async()=>{if(confirm('Deze klus verwijderen?')){await JKDB.remove('jobs',j.id);closeModal();render();}})
  }
  async function showJob(id){
    const j=await JKDB.get('jobs',id); if(!j)return; const check=j.checklistId?await JKDB.get('checklists',j.checklistId):null; const entries=(await JKDB.all('timeEntries')).filter(e=>e.jobId===id);
    const checkHtml=check?check.items.map((it,i)=>`<label class="checkline"><input type="checkbox" data-check="${i}" ${j.checklistState?.[i]?'checked':''}><span>${esc(it)}</span></label>`).join(''):'<div class="muted small">Geen checklist gekoppeld.</div>';
    modal(`${modalHead(j.title)}<div class="card"><div class="muted small">${esc(j.clientName||'Geen klant')}</div><h3>${esc(j.title)}</h3><div class="small">${fmtDate(j.date)}${j.address?' · '+esc(j.address):''}</div>${j.notes?`<p>${esc(j.notes).replace(/\n/g,'<br>')}</p>`:''}<div class="button-row"><button class="secondary" id="editThisJob">Bewerken</button><button class="primary" id="timeThisJob">Start uren</button></div></div>
      <div class="section-title"><h2>Checklist</h2></div><div class="card">${checkHtml}</div>
      <div class="section-title"><h2>Uren</h2><span class="muted small">${(entries.reduce((s,e)=>s+entryMs(e),0)/3600000).toFixed(2).replace('.',',')} u</span></div>${entries.length?`<div class="list">${entries.map(e=>`<div class="list-item"><div><div class="title">${fmtDateTime(e.start)}</div><div class="sub">${e.end?fmtDateTime(e.end):'loopt nu'}</div></div><strong>${duration(entryMs(e)).slice(0,5)}</strong></div>`).join('')}</div>`:'<div class="empty">Nog geen uren.</div>'}`);
    $('#editThisJob').addEventListener('click',()=>{closeModal();editJob(j.id)}); $('#timeThisJob').addEventListener('click',()=>{closeModal();startTimerForJob(j)});
    $$('[data-check]').forEach(c=>c.addEventListener('change',async()=>{j.checklistState=j.checklistState||{};j.checklistState[c.dataset.check]=c.checked;await JKDB.put('jobs',j)}));
  }

  async function renderGear(){
    title('Materiaal');
    const search=`<input class="search" id="gearSearch" placeholder="Zoek Mbox, machine, accu…" />`;
    $('#view').innerHTML=`<div class="tabs"><button class="tab ${state.gearTab==='mboxes'?'active':''}" data-gt="mboxes">Mboxen & organizers</button><button class="tab ${state.gearTab==='tools'?'active':''}" data-gt="tools">Gereedschap</button></div>${search}<div id="gearContent"></div>`;
    $$('[data-gt]').forEach(b=>b.addEventListener('click',()=>{state.gearTab=b.dataset.gt;renderGear()})); $('#gearSearch').addEventListener('input',renderGearContent); await renderGearContent();
  }
  async function renderGearContent(){const q=($('#gearSearch')?.value||'').toLowerCase(), box=$('#gearContent'); if(!box)return;
    if(state.gearTab==='mboxes'){
      const rows=(await JKDB.all('mboxes')).filter(m=>(m.name+' '+m.type+' '+m.items.join(' ')).toLowerCase().includes(q)); box.innerHTML=`<div class="button-row"><button class="primary" id="addMbox">+ Koffer/organizer</button></div><div class="section-title"><h2>${rows.length} items</h2></div><div class="list">${rows.map(m=>`<div class="list-item" data-mbox="${m.id}"><div class="main"><div class="title">${esc(m.name)} · ${esc(m.type)}</div><div class="sub">${m.items.length} onderdelen · ${esc(m.items.slice(0,2).join(', '))}${m.items.length>2?'…':''}</div></div><span>›</span></div>`).join('')}</div>`; $('#addMbox').addEventListener('click',()=>editMbox()); $$('[data-mbox]').forEach(x=>x.addEventListener('click',()=>editMbox(x.dataset.mbox)));
    } else {
      const mboxes=await JKDB.all('mboxes'); const map=Object.fromEntries(mboxes.map(m=>[m.id,`${m.name} · ${m.type}`])); const rows=(await JKDB.all('tools')).filter(t=>(t.name+' '+t.category+' '+(map[t.location]||t.location)).toLowerCase().includes(q)); box.innerHTML=`<div class="button-row"><button class="primary" id="addTool">+ Gereedschap</button></div><div class="section-title"><h2>${rows.length} geregistreerd</h2></div><div class="list">${rows.map(t=>`<div class="list-item" data-tool="${t.id}"><div class="main"><div class="title">${esc(t.name)}</div><div class="sub">${esc(t.category)} · ${esc(map[t.location]||'Los / vrij')}</div></div><span>›</span></div>`).join('')}</div>`; $('#addTool').addEventListener('click',()=>editTool()); $$('[data-tool]').forEach(x=>x.addEventListener('click',()=>editTool(x.dataset.tool)));
    }
  }
  async function editMbox(id){const m=id?await JKDB.get('mboxes',id):{id:JKDB.id('mbox'),name:'Mbox',type:'',items:[],notes:''};modal(`${modalHead(id?'Koffer bewerken':'Nieuwe koffer')}<form id="mboxForm"><div class="form-grid"><div class="field"><label>Naam</label><input name="name" value="${esc(m.name)}"></div><div class="field"><label>Type / inhoud</label><input name="type" value="${esc(m.type)}"></div><div class="field full"><label>Inhoud (één regel per onderdeel)</label><textarea name="items" style="min-height:220px">${esc(m.items.join('\n'))}</textarea></div><div class="field full"><label>Notities</label><textarea name="notes">${esc(m.notes||'')}</textarea></div></div><div class="button-row"><button class="primary">Opslaan</button>${id?'<button type="button" id="delMbox" class="danger-btn">Verwijderen</button>':''}</div></form>`);$('#mboxForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);Object.assign(m,{name:f.get('name'),type:f.get('type'),items:String(f.get('items')).split('\n').map(x=>x.trim()).filter(Boolean),notes:f.get('notes'),updatedAt:new Date().toISOString()});await JKDB.put('mboxes',m);closeModal();toast('Opgeslagen');renderGearContent();});$('#delMbox')?.addEventListener('click',async()=>{if(confirm('Koffer verwijderen?')){await JKDB.remove('mboxes',m.id);closeModal();renderGearContent();}})}
  async function editTool(id){const t=id?await JKDB.get('tools',id):{id:JKDB.id('tool'),name:'',category:'',location:'los',serial:'',purchaseDate:'',notes:''};const boxes=await JKDB.all('mboxes');modal(`${modalHead(id?'Gereedschap bewerken':'Nieuw gereedschap')}<form id="toolForm"><div class="field"><label>Naam</label><input name="name" required value="${esc(t.name)}"></div><div class="form-grid"><div class="field"><label>Categorie</label><input name="category" value="${esc(t.category)}"></div><div class="field"><label>Locatie</label><select name="location"><option value="los">Los / vrij</option>${boxes.map(m=>`<option value="${m.id}" ${m.id===t.location?'selected':''}>${esc(m.name+' · '+m.type)}</option>`).join('')}</select></div><div class="field"><label>Serienummer</label><input name="serial" value="${esc(t.serial||'')}"></div><div class="field"><label>Aanschafdatum</label><input type="date" name="purchaseDate" value="${esc(t.purchaseDate||'')}"></div><div class="field full"><label>Notities</label><textarea name="notes">${esc(t.notes||'')}</textarea></div></div><div class="button-row"><button class="primary">Opslaan</button>${id?'<button type="button" id="delTool" class="danger-btn">Verwijderen</button>':''}</div></form>`);$('#toolForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);['name','category','location','serial','purchaseDate','notes'].forEach(k=>t[k]=f.get(k));await JKDB.put('tools',t);closeModal();toast('Opgeslagen');renderGearContent();});$('#delTool')?.addEventListener('click',async()=>{if(confirm('Gereedschap verwijderen?')){await JKDB.remove('tools',t.id);closeModal();renderGearContent();}})}

  async function renderDocuments(){
    title('Documenten');
    $('#view').innerHTML=`<div class="tabs"><button class="tab ${state.docTab==='templates'?'active':''}" data-dt="templates">PDF-sjablonen</button><button class="tab ${state.docTab==='made'?'active':''}" data-dt="made">Gemaakte PDF's</button></div><div id="docContent"></div>`;
    $$('[data-dt]').forEach(b=>b.addEventListener('click',()=>{state.docTab=b.dataset.dt;renderDocuments()})); await renderDocContent();
  }
  async function renderDocContent(){const c=$('#docContent');if(!c)return;
    if(state.docTab==='templates'){
      const ts=await JKDB.all('pdfTemplates');c.innerHTML=`<div class="warning"><strong>Jouw eigen invulbare PDF's</strong><br><span class="small">Importeer je offerte- en factuursjabloon één keer. De app leest de bestaande formuliervelden uit en kan daarna nieuwe PDF's maken.</span></div><div class="button-row"><button class="primary" id="addTemplate">+ PDF-sjabloon importeren</button></div><div class="section-title"><h2>Sjablonen</h2></div>${ts.length?`<div class="list">${ts.map(t=>`<div class="list-item" data-template="${t.id}"><div class="main"><div class="title">${esc(t.name)}</div><div class="sub">${t.fields?.length||0} invulvelden · ${esc(t.kind||'PDF')}</div></div><span>›</span></div>`).join('')}</div>`:'<div class="empty">Importeer straks jouw twee invulbare PDF-bestanden.</div>'}`;$('#addTemplate').addEventListener('click',()=>$('#hiddenPdfInput').click());$$('[data-template]').forEach(x=>x.addEventListener('click',()=>showTemplate(x.dataset.template)));
    } else {
      const docs=(await JKDB.all('documents')).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));c.innerHTML=`<div class="button-row"><button class="secondary" id="importExistingPdfs">Importeer bestaande PDF's uit iCloud</button></div><div class="section-title"><h2>Documenten</h2></div>${docs.length?`<div class="list">${docs.map(d=>`<div class="list-item" data-doc="${d.id}"><div class="document-card"><div class="doc-icon">PDF</div><div class="main"><div class="title">${esc(d.filename)}</div><div class="sub">${fmtDateTime(d.createdAt)} · ${esc(d.templateName||'PDF')}</div></div></div><span>›</span></div>`).join('')}</div>`:`<div class="empty">Nog geen PDF's in de app.</div>`}`;$('#importExistingPdfs').addEventListener('click',()=>$('#hiddenExistingPdfInput').click());$$('[data-doc]').forEach(x=>x.addEventListener('click',()=>showDocument(x.dataset.doc)));
    }
  }
  function pdfFieldType(f){
    if(f instanceof PDFLib.PDFTextField) return 'PDFTextField';
    if(f instanceof PDFLib.PDFCheckBox) return 'PDFCheckBox';
    if(f instanceof PDFLib.PDFDropdown) return 'PDFDropdown';
    if(f instanceof PDFLib.PDFRadioGroup) return 'PDFRadioGroup';
    if(f instanceof PDFLib.PDFOptionList) return 'PDFOptionList';
    if(f instanceof PDFLib.PDFButton) return 'PDFButton';
    if(PDFLib.PDFSignature && f instanceof PDFLib.PDFSignature) return 'PDFSignature';
    return 'PDFField';
  }
  async function importExistingPdfs(files){
    let count=0;
    for(const file of files){
      if(file.type!=='application/pdf' && !file.name.toLowerCase().endsWith('.pdf')) continue;
      await JKDB.put('documents',{id:JKDB.id('doc'),filename:file.name,templateId:'',templateName:'Geïmporteerd uit iCloud',kind:/factu/i.test(file.name)?'Factuur':/offert/i.test(file.name)?'Offerte':'PDF',values:{},blob:new Blob([await file.arrayBuffer()],{type:'application/pdf'}),createdAt:new Date().toISOString()});
      count++;
    }
    toast(`${count} PDF${count===1?'':'s'} geïmporteerd`);
    state.docTab='made'; await renderDocuments();
  }
  async function importPdfTemplate(file){
    try{await ensurePdfLib(); const bytes=await file.arrayBuffer();const pdf=await PDFLib.PDFDocument.load(bytes,{ignoreEncryption:false});const form=pdf.getForm();const fields=form.getFields().map(f=>{let options=[];try{options=f.getOptions?.()||[]}catch{} return {name:f.getName(),label:f.getName(),type:pdfFieldType(f),options,defaultValue:''};});
      if(!fields.length){alert('Deze PDF bevat geen herkenbare invulbare AcroForm-velden. Upload bij voorkeur de originele invulbare PDF.');return;}
      const rec={id:JKDB.id('tpl'),name:file.name.replace(/\.pdf$/i,''),kind:/factu/i.test(file.name)?'Factuur':/offert/i.test(file.name)?'Offerte':'PDF',blob:new Blob([bytes],{type:'application/pdf'}),fields,createdAt:new Date().toISOString()};await JKDB.put('pdfTemplates',rec);toast(`${fields.length} velden gevonden`);state.docTab='templates';go('documents');
    }catch(e){console.error(e);alert('Deze PDF kon niet als invulbaar sjabloon worden gelezen. '+e.message)}
  }
  async function showTemplate(id){const t=await JKDB.get('pdfTemplates',id);modal(`${modalHead(t.name)}<div class="card"><span class="pill">${esc(t.kind)}</span><h3 style="margin-top:10px">${t.fields.length} invulvelden gevonden</h3><p class="muted small">Je kunt de zichtbare labels en vaste standaardwaarden aanpassen. De echte PDF-veldnaam blijft intact.</p><div class="button-row"><button class="primary" id="newFromTpl">Nieuwe PDF maken</button><button class="secondary" id="editTpl">Velden instellen</button></div></div><div class="button-row"><button class="danger-btn" id="delTpl">Sjabloon verwijderen</button></div>`);$('#newFromTpl').addEventListener('click',()=>{closeModal();createFromTemplate(t.id)});$('#editTpl').addEventListener('click',()=>configureTemplate(t.id));$('#delTpl').addEventListener('click',async()=>{if(confirm('Sjabloon verwijderen?')){await JKDB.remove('pdfTemplates',t.id);closeModal();renderDocContent();}})}
  async function configureTemplate(id){const t=await JKDB.get('pdfTemplates',id);modal(`${modalHead('Velden instellen')}<form id="tplCfg"><div class="field"><label>Naam sjabloon</label><input name="templateName" value="${esc(t.name)}"></div><div class="field"><label>Soort</label><select name="kind"><option ${t.kind==='Offerte'?'selected':''}>Offerte</option><option ${t.kind==='Factuur'?'selected':''}>Factuur</option><option ${t.kind==='PDF'?'selected':''}>PDF</option></select></div><div class="hr"></div>${t.fields.map((f,i)=>`<div class="card"><div class="small muted"><span class="codeish">${esc(f.name)}</span> · ${esc(f.type)}</div><div class="field"><label>Label in app</label><input name="label_${i}" value="${esc(f.label)}"></div><div class="field"><label>Standaardwaarde (optioneel)</label><input name="default_${i}" value="${esc(f.defaultValue||'')}"></div></div>`).join('')}<button class="primary" style="width:100%">Instellingen opslaan</button></form>`);$('#tplCfg').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target);t.name=fd.get('templateName');t.kind=fd.get('kind');t.fields.forEach((f,i)=>{f.label=fd.get(`label_${i}`);f.defaultValue=fd.get(`default_${i}`)});await JKDB.put('pdfTemplates',t);closeModal();toast('Sjabloon bijgewerkt');renderDocContent();})}
  function fieldInput(f,i){const v=esc(f.defaultValue||'');if(f.type.includes('CheckBox'))return `<label class="checkline"><input type="checkbox" name="field_${i}" value="1" ${f.defaultValue===true||f.defaultValue==='true'?'checked':''}><span>${esc(f.label)}</span></label>`;if((f.type.includes('Dropdown')||f.type.includes('RadioGroup')||f.type.includes('OptionList'))&&f.options?.length)return `<div class="field"><label>${esc(f.label)}</label><select name="field_${i}"><option value="">—</option>${f.options.map(o=>`<option ${o===f.defaultValue?'selected':''}>${esc(o)}</option>`).join('')}</select></div>`;return `<div class="field"><label>${esc(f.label)}</label><input name="field_${i}" value="${v}"></div>`}
  async function createFromTemplate(id){const t=await JKDB.get('pdfTemplates',id);const suggested=`${t.kind}-${new Date().toISOString().slice(0,10)}.pdf`;modal(`${modalHead(`Nieuwe ${t.kind.toLowerCase()}`)}<form id="pdfForm"><div class="field"><label>Bestandsnaam</label><input name="filename" value="${esc(suggested)}" required></div>${t.fields.map((f,i)=>(f.type.includes('Button')||f.type.includes('Signature'))?'':fieldInput(f,i)).join('')}<button class="primary" style="width:100%">PDF maken</button></form>`);$('#pdfForm').addEventListener('submit',async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;btn.textContent='PDF maken…';try{const fd=new FormData(e.target),values={};t.fields.forEach((f,i)=>values[f.name]=f.type.includes('CheckBox')?fd.get(`field_${i}`)==='1':(fd.get(`field_${i}`)??''));const blob=await fillPdf(t,values);let filename=String(fd.get('filename')||suggested);if(!filename.toLowerCase().endsWith('.pdf'))filename+='.pdf';const d={id:JKDB.id('doc'),filename,templateId:t.id,templateName:t.name,kind:t.kind,values,blob,createdAt:new Date().toISOString()};await JKDB.put('documents',d);closeModal();toast('PDF aangemaakt');await shareBlob(blob,filename);state.docTab='made';renderDocuments();}catch(err){console.error(err);alert('PDF maken lukte niet: '+err.message);btn.disabled=false;btn.textContent='PDF maken';}})}
  async function fillPdf(t,values){await ensurePdfLib(); const bytes=await t.blob.arrayBuffer();const pdf=await PDFLib.PDFDocument.load(bytes);const form=pdf.getForm();for(const f of t.fields){let field;try{field=form.getField(f.name)}catch{continue}const v=values[f.name];try{if(f.type.includes('TextField'))field.setText(String(v??''));else if(f.type.includes('CheckBox'))v?field.check():field.uncheck();else if(f.type.includes('Dropdown')||f.type.includes('RadioGroup')){if(v)field.select(String(v));}else if(f.type.includes('OptionList')){if(v)field.select(String(v));}}catch(err){console.warn('Veld overgeslagen',f.name,err)}}try{const font=await pdf.embedFont(PDFLib.StandardFonts.Helvetica);form.updateFieldAppearances(font)}catch{}const out=await pdf.save();return new Blob([out],{type:'application/pdf'})}
  async function showDocument(id){const d=await JKDB.get('documents',id);modal(`${modalHead(d.filename)}<div class="card"><div class="document-card"><div class="doc-icon">PDF</div><div><h3>${esc(d.filename)}</h3><div class="muted small">${esc(d.kind||'PDF')} · ${fmtDateTime(d.createdAt)}</div></div></div><div class="button-row" style="margin-top:14px"><button class="primary" id="shareDoc">Delen / bewaar in iCloud</button><button class="secondary" id="downloadDoc">Download</button></div></div><button class="danger-btn" id="delDoc" style="width:100%">Uit app verwijderen</button>`);$('#shareDoc').addEventListener('click',()=>shareBlob(d.blob,d.filename));$('#downloadDoc').addEventListener('click',()=>downloadBlob(d.blob,d.filename));$('#delDoc').addEventListener('click',async()=>{if(confirm('Deze PDF uit de app verwijderen? Dit verwijdert geen kopie die al in iCloud staat.')){await JKDB.remove('documents',id);closeModal();renderDocContent();}})}
  async function shareBlob(blob,filename){const file=new File([blob],filename,{type:blob.type||'application/pdf'});try{if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({files:[file]});return}}catch(e){if(e.name==='AbortError')return;}downloadBlob(blob,filename)}
  function downloadBlob(blob,filename){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}

  async function renderMore(){title('Meer');const [checks,clients,entries,company,backup]=await Promise.all([JKDB.all('checklists'),JKDB.all('clients'),JKDB.all('timeEntries'),JKDB.get('settings','company'),JKDB.get('settings','backup')]);const run=entries.find(e=>!e.end);$('#view').innerHTML=`
    <div class="list">
      <div class="list-item clickable" id="timeMenu"><div class="main"><div class="title">⏱ Urenregistratie</div><div class="sub">${run?'Timer loopt · '+esc(run.jobTitle||'algemeen'):entries.length+' registraties'}</div></div><span>›</span></div>
      <div class="list-item clickable" id="checkMenu"><div class="main"><div class="title">✅ Checklists</div><div class="sub">${checks.length} checklists</div></div><span>›</span></div>
      <div class="list-item clickable" id="clientMenu"><div class="main"><div class="title">👥 Klanten</div><div class="sub">${clients.length} klanten</div></div><span>›</span></div>
      <div class="list-item clickable" id="companyMenu"><div class="main"><div class="title">🏢 Bedrijfsgegevens</div><div class="sub">${esc(company?.companyName||'JK Works Dordrecht')}</div></div><span>›</span></div>
      <div class="list-item clickable" id="backupMenu"><div class="main"><div class="title">☁️ Back-up & herstel</div><div class="sub">${backup?.lastBackup?'Laatst: '+fmtDateTime(backup.lastBackup):'Nog geen back-up gemaakt'}</div></div><span>›</span></div>
      <div class="list-item clickable" id="installMenu"><div class="main"><div class="title">📱 Installatie & iCloud</div><div class="sub">Uitleg voor iPhone en MacBook</div></div><span>›</span></div>
    </div>`;$('#timeMenu').addEventListener('click',showTimeEntries);$('#checkMenu').addEventListener('click',showChecklists);$('#clientMenu').addEventListener('click',showClients);$('#companyMenu').addEventListener('click',showCompany);$('#backupMenu').addEventListener('click',showBackup);$('#installMenu').addEventListener('click',showInstallInfo)}

  async function showClients(){const cs=(await JKDB.all('clients')).sort((a,b)=>a.name.localeCompare(b.name));modal(`${modalHead('Klanten')}<button class="primary" id="addClient" style="width:100%;margin-bottom:12px">+ Nieuwe klant</button><div class="list">${cs.length?cs.map(c=>`<div class="list-item" data-client="${c.id}"><div class="main"><div class="title">${esc(c.name)}</div><div class="sub">${esc([c.city,c.phone].filter(Boolean).join(' · ')||'Geen extra gegevens')}</div></div><span>›</span></div>`).join(''):'<div class="empty">Nog geen klanten.</div>'}</div>`);$('#addClient').addEventListener('click',()=>editClient());$$('[data-client]').forEach(x=>x.addEventListener('click',()=>editClient(x.dataset.client)))}
  async function editClient(id){const c=id?await JKDB.get('clients',id):{id:JKDB.id('client'),name:'',street:'',postal:'',city:'',phone:'',email:'',notes:''};modal(`${modalHead(id?'Klant bewerken':'Nieuwe klant')}<form id="clientForm"><div class="field"><label>Naam</label><input name="name" required value="${esc(c.name)}"></div><div class="field"><label>Straat + huisnummer</label><input name="street" value="${esc(c.street||'')}"></div><div class="form-grid"><div class="field"><label>Postcode</label><input name="postal" value="${esc(c.postal||'')}"></div><div class="field"><label>Plaats</label><input name="city" value="${esc(c.city||'')}"></div><div class="field"><label>Telefoon</label><input type="tel" name="phone" value="${esc(c.phone||'')}"></div><div class="field"><label>E-mail</label><input type="email" name="email" value="${esc(c.email||'')}"></div><div class="field full"><label>Notities</label><textarea name="notes">${esc(c.notes||'')}</textarea></div></div><div class="button-row"><button class="primary">Opslaan</button>${id?'<button type="button" class="danger-btn" id="delClient">Verwijderen</button>':''}</div></form>`);$('#clientForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);['name','street','postal','city','phone','email','notes'].forEach(k=>c[k]=f.get(k));await JKDB.put('clients',c);closeModal();toast('Klant opgeslagen');state.route==='jobs'?render():null});$('#delClient')?.addEventListener('click',async()=>{if(confirm('Klant verwijderen?')){await JKDB.remove('clients',id);closeModal();}})}
  async function showChecklists(){const cs=await JKDB.all('checklists');modal(`${modalHead('Checklists')}<button class="primary" id="addCheck" style="width:100%;margin-bottom:12px">+ Nieuwe checklist</button><div class="list">${cs.map(c=>`<div class="list-item" data-checklist="${c.id}"><div class="main"><div class="title">${esc(c.name)}</div><div class="sub">${c.items.length} punten</div></div><span>›</span></div>`).join('')}</div>`);$('#addCheck').addEventListener('click',()=>editChecklist());$$('[data-checklist]').forEach(x=>x.addEventListener('click',()=>editChecklist(x.dataset.checklist)))}
  async function editChecklist(id){const c=id?await JKDB.get('checklists',id):{id:JKDB.id('check'),name:'',items:[]};modal(`${modalHead(id?'Checklist bewerken':'Nieuwe checklist')}<form id="checkForm"><div class="field"><label>Naam</label><input name="name" required value="${esc(c.name)}"></div><div class="field"><label>Punten (één per regel)</label><textarea name="items" style="min-height:260px">${esc(c.items.join('\n'))}</textarea></div><div class="button-row"><button class="primary">Opslaan</button>${id?'<button type="button" id="delCheck" class="danger-btn">Verwijderen</button>':''}</div></form>`);$('#checkForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);c.name=f.get('name');c.items=String(f.get('items')).split('\n').map(x=>x.trim()).filter(Boolean);await JKDB.put('checklists',c);closeModal();toast('Checklist opgeslagen')});$('#delCheck')?.addEventListener('click',async()=>{if(confirm('Checklist verwijderen?')){await JKDB.remove('checklists',id);closeModal();}})}

  async function startTimerModal(){const jobs=(await JKDB.all('jobs')).filter(j=>j.status!=='afgerond');modal(`${modalHead('Uren starten')}<form id="startTimerForm"><div class="field"><label>Klus</label><select name="jobId"><option value="">Algemene werkzaamheden</option>${jobs.map(j=>`<option value="${j.id}">${esc(j.title)}${j.clientName?' · '+esc(j.clientName):''}</option>`).join('')}</select></div><div class="field"><label>Notitie</label><input name="note" placeholder="Optioneel"></div><button class="primary" style="width:100%">Start timer</button></form>`);$('#startTimerForm').addEventListener('submit',async e=>{e.preventDefault();const existing=(await JKDB.all('timeEntries')).find(x=>!x.end);if(existing){alert('Er loopt al een timer. Stop die eerst.');return}const fd=new FormData(e.target),j=jobs.find(x=>x.id===fd.get('jobId'));await JKDB.put('timeEntries',{id:JKDB.id('time'),jobId:j?.id||'',jobTitle:j?.title||'Algemene werkzaamheden',start:new Date().toISOString(),end:null,note:fd.get('note')});closeModal();toast('Timer gestart');render();})}
  async function startTimerForJob(j){const existing=(await JKDB.all('timeEntries')).find(x=>!x.end);if(existing){alert('Er loopt al een timer. Stop die eerst.');return}await JKDB.put('timeEntries',{id:JKDB.id('time'),jobId:j.id,jobTitle:j.title,start:new Date().toISOString(),end:null,note:''});toast('Timer gestart');render()}
  async function stopTimer(id){const e=await JKDB.get('timeEntries',id);if(!e)return;e.end=new Date().toISOString();await JKDB.put('timeEntries',e);toast('Timer gestopt');render()}
  async function showTimeEntries(){const es=(await JKDB.all('timeEntries')).sort((a,b)=>b.start.localeCompare(a.start)),run=es.find(e=>!e.end);modal(`${modalHead('Urenregistratie')}${run?`<div class="card"><div class="metric-label">TIMER LOOPT</div><div class="timer" id="modalTimer">${duration(entryMs(run))}</div><div class="muted small">${esc(run.jobTitle)}</div><button class="danger-btn" id="stopModalTimer" style="width:100%;margin-top:12px">Stop timer</button></div>`:`<button class="primary" id="startModalTimer" style="width:100%;margin-bottom:12px">▶ Start uren</button>`}<div class="list">${es.length?es.map(e=>`<div class="list-item"><div class="main"><div class="title">${esc(e.jobTitle||'Algemeen')}</div><div class="sub">${fmtDateTime(e.start)}${e.end?' → '+fmtDateTime(e.end):' · loopt'}</div></div><strong>${duration(entryMs(e)).slice(0,5)}</strong></div>`).join(''):'<div class="empty">Nog geen uren geregistreerd.</div>'}</div>`);if(run){$('#stopModalTimer').addEventListener('click',async()=>{closeModal();await stopTimer(run.id)});state.timerTick=setInterval(()=>{const el=$('#modalTimer');if(el)el.textContent=duration(entryMs(run));},1000)}else $('#startModalTimer').addEventListener('click',()=>{closeModal();startTimerModal()})}

  async function showCompany(){const c=await JKDB.get('settings','company');modal(`${modalHead('Bedrijfsgegevens')}<form id="companyForm"><div class="field"><label>Bedrijfsnaam</label><input name="companyName" value="${esc(c.companyName||'')}"></div><div class="field"><label>Naam</label><input name="owner" value="${esc(c.owner||'')}"></div><label class="checkline"><input type="checkbox" name="kor" ${c.kor?'checked':''}><span>Kleineondernemersregeling (KOR) actief</span></label><div class="field"><label>KOR sinds</label><input type="date" name="korSince" value="${esc(c.korSince||'')}"></div><div class="field"><label>Standaard uurtarief</label><input type="number" step="0.01" name="defaultRate" value="${esc(c.defaultRate||'')}"></div><div class="field"><label>Notities</label><textarea name="notes">${esc(c.notes||'')}</textarea></div><button class="primary" style="width:100%">Opslaan</button></form>`);$('#companyForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);Object.assign(c,{companyName:f.get('companyName'),owner:f.get('owner'),kor:f.get('kor')==='on',korSince:f.get('korSince'),defaultRate:f.get('defaultRate'),notes:f.get('notes')});await JKDB.put('settings',c);closeModal();toast('Bedrijfsgegevens opgeslagen');render()})}
  function showBackup(){modal(`${modalHead('Back-up & herstel')}<div class="card"><h3>iCloud-back-up maken</h3><p class="muted small">Maakt één bestand met je appgegevens, PDF-sjablonen en aangemaakte PDF's. Bewaar dit via de deelkaart in iCloud Drive.</p><button class="primary" id="exportBackup" style="width:100%">Maak volledige back-up</button></div><div class="card"><h3>Back-up terugzetten</h3><p class="muted small">Let op: dit vervangt de huidige lokale appgegevens.</p><button class="secondary" id="importBackup" style="width:100%">Kies back-upbestand</button></div>`);$('#exportBackup').addEventListener('click',exportBackup);$('#importBackup').addEventListener('click',()=>$('#hiddenBackupInput').click())}
  async function blobToDataURL(blob){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(blob)})}
  async function serializeRecord(r){const o={...r};for(const k of Object.keys(o))if(o[k] instanceof Blob)o[k]={__blob:true,type:o[k].type,data:await blobToDataURL(o[k])};return o}
  function dataURLToBlob(url){const [meta,b64]=url.split(',');const mime=/data:(.*?);base64/.exec(meta)?.[1]||'application/octet-stream';const bin=atob(b64),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return new Blob([a],{type:mime})}
  async function exportBackup(){try{const payload={format:'JKWORKS_BACKUP_V1',createdAt:new Date().toISOString(),stores:{}};for(const s of JKDB.stores){payload.stores[s]=[];for(const r of await JKDB.all(s))payload.stores[s].push(await serializeRecord(r))}const blob=new Blob([JSON.stringify(payload)],{type:'application/json'}),name=`JK-Works-backup-${new Date().toISOString().slice(0,10)}.jkbackup.json`;await JKDB.put('settings',{id:'backup',lastBackup:new Date().toISOString()});closeModal();await shareBlob(blob,name);toast('Back-up gemaakt');render()}catch(e){alert('Back-up maken lukte niet: '+e.message)}}
  async function restoreBackup(file){try{const p=JSON.parse(await file.text());if(p.format!=='JKWORKS_BACKUP_V1')throw new Error('Onbekend back-upformaat');if(!confirm('Huidige appgegevens vervangen door deze back-up?'))return;for(const s of JKDB.stores){await JKDB.clear(s);for(const rec of (p.stores[s]||[])){for(const k of Object.keys(rec))if(rec[k]?.__blob)rec[k]=dataURLToBlob(rec[k].data);await JKDB.put(s,rec)}}await JKDB.put('settings',{id:'backup',lastBackup:new Date().toISOString()});toast('Back-up teruggezet');go('dashboard')}catch(e){alert('Terugzetten mislukt: '+e.message)}}
  function showInstallInfo(){modal(`${modalHead('Installatie & iCloud')}<div class="card"><h3>Op iPhone installeren</h3><p class="small">1. Open de gepubliceerde app-link in Safari.<br>2. Tik op Deel.<br>3. Kies <strong>Zet op beginscherm</strong>.<br>4. Open daarna JK Works via het nieuwe app-icoon.</p></div><div class="card"><h3>PDF naar iCloud Drive</h3><p class="small">Na het maken van een PDF tik je op <strong>Delen / bewaar in iCloud</strong>. Kies daarna <strong>Bewaar in Bestanden</strong> en jouw map in iCloud Drive. Je kunt in iPhone-instellingen ook Safari-downloads standaard in iCloud Drive laten opslaan.</p></div><div class="card"><h3>Offline</h3><p class="small">De app en je gegevens werken lokaal. Voor de ingebouwde PDF-module is één eerste online laadbeurt nodig; daarna wordt die door de web-app gecachet.</p></div>`)}

  async function quickAdd(){modal(`${modalHead('Snel toevoegen')}<div class="grid two"><button class="quick" id="qaJob"><span class="emoji">👷</span><strong>Nieuwe klus</strong></button><button class="quick" id="qaClient"><span class="emoji">👤</span><strong>Nieuwe klant</strong></button><button class="quick" id="qaTime"><span class="emoji">⏱</span><strong>Uren starten</strong></button><button class="quick" id="qaPdf"><span class="emoji">📄</span><strong>PDF-sjabloon</strong></button></div>`);$('#qaJob').addEventListener('click',()=>{closeModal();editJob()});$('#qaClient').addEventListener('click',()=>{closeModal();editClient()});$('#qaTime').addEventListener('click',()=>{closeModal();startTimerModal()});$('#qaPdf').addEventListener('click',()=>{closeModal();$('#hiddenPdfInput').click()})}

  return {init,go};
})();

document.addEventListener('DOMContentLoaded',()=>App.init());
